<?php /* @var $this Mage_Customer_Block_Account_Dashboard_Address */ ?>
<div class="wdn-col">
    <h3 class="clear-top">Address Book</h3>
    <ul class="mrkp-list-flat">
       <li><a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a></li>
       <li><a href="<?php echo $this->getUrl('customer/address/new'); ?>">Add New Address</a></li>
    </ul>
</div>
