<?php /* @var $this Mage_Core_Block_Template */ ?>
</h2>
			</div></td>
	</tr>
	<tr>
		<td colspan="2">
			<img src="<?php echo $this->getSkinUrl() ?>images/email/email_06.gif" width="556" height="25" alt="" /></td>
	</tr>
	<tr>
		<td style="background-color:#005288;">
			<div style="width:12px;">&nbsp;</div></td>
		<td style="background-color:#FFFFFF;">
			<div style="width:10px;">&nbsp;</div></td>
		<td colspan="2" valign="top">
			<div style="width:556px;overflow:hidden;color:#333333;font-family:Arial,sans-serif;font-size:12px;line-height:1.4;">
