<?php /* @var $this Mage_Core_Block_Template */ ?>
			</div></td>
		<td style="background-color:#FFFFFF;">
			<div style="width:10px;">&nbsp;</div></td>
		<td style="background-color:#005288;">
			<div style="width:12px;">&nbsp;</div></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="<?php echo $this->getSkinUrl() ?>images/email/email_12.gif" width="600" height="51" alt="" style="display:block;" /></td>
	</tr>
	<tr>
		<td style="background-color:#005288;" colspan="2">
			<div style="width:22px;">&nbsp;</div></td>
		<td style="background-color:#005288;" colspan="2">
			<div style="color:#FFFFFF;font-size:10px;line-height:1.1;font-family:Arial,sans-serif;min-height:42px;">
				<p>&copy; 2012 Buros Center for Testing<br />
				21 Teachers College Hall | Lincoln, NE 68588-0348 | 402-472-6203</p>
			</div></td>
		<td style="background-color:#005288;" colspan="2">
			<div style="width:22px;">&nbsp;</div></td>
	</tr>
	<tr>
		<td colspan="6">
			<img src="<?php echo $this->getSkinUrl() ?>images/email/email_16.gif" width="600" height="12" alt="" style="display:block;" /></td>
	</tr>
</table>
</td>
</tr>
</table>
</div>
</body>