<?php /* @var $this Mage_Core_Block_Template */ ?>
<div style="background-color:#13151E;padding-top:10px;padding-bottom:10px;overflow:auto;">
<table cellspacing="0" cellpadding="0" border="0" width="98%">
<tr>
<td align="center" valign="top">
<table width="600" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
	<tr>
		<td colspan="2" rowspan="3">
			<img src="<?php echo $this->getSkinUrl() ?>images/email/email_01.gif" width="22" height="95" alt="" /></td>
		<td rowspan="2">
			<img src="<?php echo $this->getSkinUrl() ?>images/email/email_02.gif" width="163" height="70" alt="" /></td>
		<td>
			<img src="<?php echo $this->getSkinUrl() ?>images/email/email_03.gif" width="393" height="31" alt="" /></td>
		<td colspan="2" rowspan="3">
			<img src="<?php echo $this->getSkinUrl() ?>images/email/email_04.gif" width="22" height="95" alt="" /></td>
	</tr>
	<tr>
		<td>
			<div style="height:39px;overflow:hidden;">
				<h1 style="color:#565656;font-family:Helvetica,Arial;text-decoration:none;font-size:27px;line-height:1;font-weight:bold;margin:0;margin-top:3px;">TEST REVIEWS ONLINE</h1>
				<h2 style="color:#565656;font-family:Helvetica,Arial;text-decoration:none;font-size:10px;line-height:1;font-weight:normal;margin:0;padding-top:0px;padding-bottom:0;">
