<?php
/* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */
?>
<?php
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?>
<?php if ($_items): ?>
<div class="block block-list block-compare wdn-band">
    <div class="wdn-inner-wrapper"><div class="wdn-grid-set">
    <div class="block-title bp2-wdn-col-one-fifth">
        <strong><span><?php echo $this->__('Compare Products') ?></span></strong>
    </div>
    <div class="block-content bp2-wdn-col-four-fifths">
        <div class="wdn-grid-set">
        <div class="wdn-col-five-sevenths">
        <ol id="compare-items" class="wdn-grid-set-fifths">
        <?php foreach($_items as $_index => $_item): ?>
            <li class="item wdn-col">
                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                <a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"><i class="mrkp-icon-cancel-circled"></i></a>
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(64) ?>" alt="<?php echo $this->escapeHtml($this->getImageLabel($_item)) ?>" />
                </a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        </div>
        <div class="actions wdn-col-two-sevenths">
            <a href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');" title="<?php echo $this->__('Clear All') ?>" class="wdn-button"><i class="mrkp-icon-cancel-circled"></i></a>
            <button type="button" title="<?php echo $this->__('Compare') ?>" class="button" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo $this->__('Compare') ?></span></span></button>
        </div>
        </div>
    </div>
    </div></div>
</div>
<?php endif; ?>
