<?php
/**
 * Store switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */
?>
<?php if(count($this->getGroups())>1): ?>
<ul>
    <?php foreach ($this->getGroups() as $_group): ?>
    <?php if (!$_group->getIsHidden() && !in_array('default', $_group->getStoreCodes())): ?>
        <li><a href="<?php echo $_group->getHomeUrl() ?>"><?php echo $this->htmlEscape($_group->getName()) ?></a></li>
    <?php endif; ?>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
