<?php $_item = $this->getItem() ?>
<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th align="left" bgcolor="#ba0000" style="padding:3px 9px;line-height:1em;color:#FFF;font-size:12px;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Item') ?></th>
            <th align="left" bgcolor="#ba0000" style="padding:3px 9px;line-height:1em;color:#FFF;font-size:12px;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Sku') ?></th>
            <th align="center" bgcolor="#ba0000" style="padding:3px 9px;line-height:1em;color:#FFF;font-size:12px;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Qty') ?></th>
        </tr>
    </thead>

    <tbody>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>

</table>
