<?php
/* @var $this Mage_Catalog_Block_Product_List_Upsell */
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    <ul class="products-grid wdn-grid-set-fourths" id="upsell-product-table">
    <?php foreach($this->getItems() as $_link): ?>
        <li class="item wdn-col">
            <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(223) ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
            <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
            <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
            <?php echo $this->getReviewsSummaryHtml($_link) ?>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('upsell-product-table')</script>
</div>
<?php endif ?>
