<?php
/**
 * Customer login form template
 *
 * @see app/design/frontend/base/default/template/customer/form/login.phtml
 */
/* @var $this Mage_Customer_Block_Form_Login */
?>
<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>
    <?php echo $errors = $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="wdn-grid-set bp1-wdn-grid-set-thirds">
            <div class="wdn-col" id="unl_login">
                <a class="mrkp-btn-cnt" href="<?php echo Mage::helper('unl_cas')->getCasUrl() ?>">
                    <i class="mrkp-icon-unl-n"></i>
                    <span class="mrkp-btn-action">Log in as</span>
                    <span class="mrkp-btn-noun">UNL <span style="display:block;font-size:.7em">student, faculty, staff</span></span>
                </a>
            </div>
            <div class="wdn-col" id="returning">
                <a class="mrkp-btn-cnt" href="#">
                    <i class="mrkp-icon-login"></i>
                    <span class="mrkp-btn-action">Log in as</span>
                    <span class="mrkp-btn-noun short">returning customer</span>
                </a>
            </div>
            <div class="bp1-wdn-col-two-thirds" id="login_inputs" style="display:none;">
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </ul>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

                <div class="buttons-set">
                    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="alt-action"><?php echo $this->__('Forgot Your Password?') ?></a>
                </div>
            </div>
            <div class="wdn-col" id="create">
                <a class="mrkp-btn-cnt" href="<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>">
                    <i class="wdn-icon-user"></i>
                    <span class="mrkp-btn-action">Create</span>
                    <span class="mrkp-btn-noun short">new account</span>
                </a>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);

        require(['jquery', 'modernizr'], function($, Modernizr) {
    		$(function() {
    			$cust = $('#returning a');
    			$cust.on('click', function(e) {
        			var unlLogin = $('#unl_login'),
        			create = $('#create'),
        			unlLoginBtn = unlLogin.children('a'),
        			loginForm = $('#login_inputs'),
        			$this = $(this),
        			st = 'state',
        			tg = 'toggle',
        			w = 'width',
        			h = 'height',
        			bp1 = '(min-width: 480px)';

        			e.preventDefault();

        			if (!$this.data(st)) {
        				$this.data(st, true);

        				var done = function() {
        					loginForm.fadeIn();
        				},
        				ani = {opacity: 0};

        				if (Modernizr.mq(bp1)) {
        					unlLoginBtn.width(unlLoginBtn.width());
            				ani[w] = tg;
        				} else {
        					ani[h] = tg;
        				}

        				unlLogin.animate(ani, done);
        				create.fadeOut();
        			} else {
        				$this.data(st, false);

        				var done = function() {
        					unlLoginBtn.css(w, '');
        				},
        				ani = {opacity: 1};

        				loginForm.fadeOut(function() {
            				if (Modernizr.mq(bp1)) {
            					ani[w] = tg;
            				} else {
            					ani[h] = tg;
            				}

            				unlLogin.animate(ani, done);
            				create.fadeIn();
        				});
        			}
        		});
    			<?php if (!empty($errors)): ?>
    			$cust.click();
    			<?php endif;?>
    		});
    	});
    //]]>
    </script>
</div>
