<?php $_product     = $this->getProduct() ?>
<?php $_priceModel  = $_product->getPriceModel() ?>
<?php list($_minimalPriceTax, $_maximalPriceTax) = $_priceModel->getTotalPrices($_product, null, null, false) ?>
<?php list($_minimalPriceInclTax, $_maximalPriceInclTax) = $_priceModel->getTotalPrices($_product, null, true, false) ?>
<?php $_id = $_product->getId() ?>

<?php $_weeeTaxAmount = 0; ?>

<?php
if ($_product->getPriceType() == 1) {
    $_weeeTaxAmount = Mage::helper('weee')->getAmount($_product);
    if ($_weeeTaxAmount && Mage::helper('weee')->typeOfDisplay($_product, array(0, 1, 4))) {
        $_minimalPriceTax += $_weeeTaxAmount;
        $_minimalPriceInclTax += $_weeeTaxAmount;
    }
    if ($_weeeTaxAmount && Mage::helper('weee')->typeOfDisplay($_product, 2)) {
        $_minimalPriceInclTax += $_weeeTaxAmount;
    }

    if (Mage::helper('weee')->typeOfDisplay($_product, array(1, 2, 4))) {
        $_weeeTaxAttributes = Mage::helper('weee')->getProductWeeeAttributesForDisplay($_product);
    }
}
?>

<div class="price-box">
        <?php if ($_product->getPriceView()): ?>
            <p class="minimal-price">
                <span class="price-label"><?php echo $this->__('As low as') ?>:</span>
                <?php if ($this->displayBothPrices() && $this->isRatesGraterThenZero()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax:') ?></span>
                        <?php echo Mage::helper('core')->currency($_minimalPriceTax) ?>
                    </span>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if (Mage::helper('weee')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('core')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <span class="price-including-tax">
                        <span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax:') ?></span>
                        <?php echo Mage::helper('core')->currency($_minimalPriceInclTax) ?>
                    </span>
            <?php else: ?>
                <?php echo Mage::helper('core')->currency($_minimalPriceTax) ?>
                <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                    <span class="weee">(<small>
                        <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                            <?php if (Mage::helper('weee')->typeOfDisplay($_product, array(2, 4))): ?>
                                <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                            <?php else: ?>
                                <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                            <?php endif; ?>

                            <?php echo $_weeeSeparator; ?>
                            <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('core')->currency($amount, true, true); ?>
                            <?php $_weeeSeparator = ' + '; ?>
                        <?php endforeach; ?>
                    </small>)</span>
                <?php endif; ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_product, 2) && $_weeeTaxAmount): ?>
                    <?php echo Mage::helper('core')->currency($_minimalPriceInclTax) ?>
                <?php endif; ?>
            <?php endif; ?>
            </p>
        <?php else: ?>
            <?php if ($_minimalPriceTax <> $_maximalPriceTax): ?>
            <p class="price-from">
                <span class="price-label"><?php echo $this->__('From') ?>:</span>
                <?php if ($this->displayBothPrices() && $this->isRatesGraterThenZero()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax:') ?></span>
                        <?php echo Mage::helper('core')->currency($_minimalPriceTax) ?>
                    </span>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if (Mage::helper('weee')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('core')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <span class="price-including-tax">
                        <span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax:') ?></span>
                        <?php echo Mage::helper('core')->currency($_minimalPriceInclTax) ?>
                    </span>
                <?php else: ?>
                    <?php echo Mage::helper('core')->currency($_minimalPriceTax) ?>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if (Mage::helper('weee')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('core')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_product, 2) && $_weeeTaxAmount): ?>
                        <?php echo Mage::helper('core')->currency($_minimalPriceInclTax) ?>
                    <?php endif; ?>
                <?php endif; ?>
            </p>
                <?php
                    if ($_product->getPriceType() == 1) {
                        if ($_weeeTaxAmount && Mage::helper('weee')->typeOfDisplay($_product, array(0, 1, 4))) {
                            $_maximalPriceTax += $_weeeTaxAmount;
                            $_maximalPriceInclTax += $_weeeTaxAmount;
                        }
                        if ($_weeeTaxAmount && Mage::helper('weee')->typeOfDisplay($_product, 2)) {
                            $_maximalPriceInclTax += $_weeeTaxAmount;
                        }
                    }
                ?>
                <p class="price-to">
                    <span class="price-label"><?php echo $this->__('To') ?>:</span>
                    <?php if ($this->displayBothPrices() && $this->isRatesGraterThenZero()): ?>
                        <span class="price-excluding-tax">
                            <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax:') ?></span>
                            <?php echo Mage::helper('core')->currency($_maximalPriceTax) ?>
                        </span>
                        <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                            <span class="weee">(<small>
                                <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                    <?php if (Mage::helper('weee')->typeOfDisplay($_product, array(2, 4))): ?>
                                        <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                    <?php else: ?>
                                        <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                    <?php endif; ?>

                                    <?php echo $_weeeSeparator; ?>
                                    <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('core')->currency($amount, true, true); ?>
                                    <?php $_weeeSeparator = ' + '; ?>
                                <?php endforeach; ?>
                            </small>)</span>
                        <?php endif; ?>
                        <span class="price-including-tax">
                            <span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax') ?></span>
                            <?php echo Mage::helper('core')->currency($_maximalPriceInclTax) ?>
                        </span>
                    <?php else: ?>
                        <?php echo Mage::helper('core')->currency($_maximalPriceTax) ?>
                        <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                            <span class="weee">(<small>
                                <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                    <?php if (Mage::helper('weee')->typeOfDisplay($_product, array(2, 4))): ?>
                                        <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                    <?php else: ?>
                                        <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                    <?php endif; ?>

                                    <?php echo $_weeeSeparator; ?>
                                    <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('core')->currency($amount, true, true); ?>
                                    <?php $_weeeSeparator = ' + '; ?>
                                <?php endforeach; ?>
                            </small>)</span>
                        <?php endif; ?>
                        <?php if (Mage::helper('weee')->typeOfDisplay($_product, 2) && $_weeeTaxAmount): ?>
                            <?php echo Mage::helper('core')->currency($_maximalPriceInclTax) ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </p>
            <?php else: ?>
                <?php if ($this->displayBothPrices() && $this->isRatesGraterThenZero()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax:') ?></span>
                        <?php echo Mage::helper('core')->currency($_minimalPriceTax) ?>
                    </span>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if (Mage::helper('weee')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('core')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <span class="price-including-tax">
                        <span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax:') ?></span>
                        <?php echo Mage::helper('core')->currency($_minimalPriceInclTax) ?>
                    </span>
                <?php else: ?>
                    <?php echo Mage::helper('core')->currency($_minimalPriceTax) ?>
                    <?php if ($_weeeTaxAmount && $_product->getPriceType() == 1 && Mage::helper('weee')->typeOfDisplay($_product, array(2, 1, 4))): ?>
                        <span class="weee">(<small>
                            <?php $_weeeSeparator = ''; foreach ($_weeeTaxAttributes as $_weeeTaxAttribute): ?>
                                <?php if (Mage::helper('weee')->typeOfDisplay($_product, array(2, 4))): ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount()+$_weeeTaxAttribute->getTaxAmount(); ?>
                                <?php else: ?>
                                    <?php $amount = $_weeeTaxAttribute->getAmount(); ?>
                                <?php endif; ?>

                                <?php echo $_weeeSeparator; ?>
                                <?php echo $_weeeTaxAttribute->getName(); ?>: <?php echo Mage::helper('core')->currency($amount, true, true); ?>
                                <?php $_weeeSeparator = ' + '; ?>
                            <?php endforeach; ?>
                        </small>)</span>
                    <?php endif; ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_product, 2) && $_weeeTaxAmount): ?>
                        <?php echo Mage::helper('core')->currency($_minimalPriceInclTax) ?>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
</div>
