<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <title><?php echo Mage::helper('unl_comm')->__('Message Preview'); ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
    <?php echo $this->getChildHtml('content') ?>
    <?php echo $this->getChildHtml('profiler') ?>
</body>
</html>