<?php /** @var $this Mage_Adminhtml_Block_Sales_Order_View_Info */?>
<?php $_order = $this->getOrder() ?>
<?php
$orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
$orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
?>
<div class="box-left">
    <!--Order Information-->
    <div class="entry-edit">
        <?php if ($_order->getEmailSent()):
            $_email = Mage::helper('sales')->__('the order confirmation email was sent');
        else:
            $_email = Mage::helper('sales')->__('the order confirmation email is not sent');
        endif; ?>
        <div class="entry-edit-head">
        <?php if ($this->getNoUseOrderLink()): ?>
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?> (<?php echo $_email ?>)</h4>
        <?php else: ?>
            <a href="<?php echo $this->getViewUrl($_order->getId()) ?>"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?></a>
            <strong>(<?php echo $_email ?>)</strong>
        <?php endif; ?>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
                <td><strong><?php echo $orderAdminDate ?></strong></td>
            </tr>
            <?php if ($orderAdminDate != $orderStoreDate):?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label></td>
                <td><strong><?php echo $orderStoreDate ?></strong></td>
            </tr>
            <?php endif;?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
                <td><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
                <td><strong><?php echo $this->getOrderStoreName() ?></strong></td>
            </tr>
            <?php if($_order->getRelationChildId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the New Order') ?></label></td>
                <td><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
                    <?php echo $_order->getRelationChildRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRelationParentId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the Previous Order') ?></label></td>
                <td><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
                    <?php echo $_order->getRelationParentRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRemoteIp()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Placed from IP') ?></label></td>
                <td><strong><?php echo $_order->getRemoteIp(); echo ($_order->getXForwardedFor())?' (' . $_order->getXForwardedFor() . ')':''; ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            <tr>
                <td class="label">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <?php
            $carrier = $_order->getShippingCarrier();
            $ship = explode('_', $_order->getShippingMethod());
            array_shift($ship);
            $ship = implode('_', $ship);
            if (!$shipmethod = $carrier->getCode('method', $ship)) {
                $shipmethod = $carrier->getShipmentByCode($ship);
            }
            ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Shipping Carrier') ?></label></td>
                <td><strong><?php echo $carrier->getConfigData('title') ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Shipping Method') ?></label></td>
                <td><strong><?php echo $shipmethod ?></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Shipping Charges') ?></label></td>
                <td><strong>
                	<?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                        <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                    <?php else: ?>
                        <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif; ?>
                    <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                    <?php echo $_excl; ?>
                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>
                </strong></td>
            </tr>
            <?php if ($_order->getAwDeliverydateDate()): ?>
            <tr>
                <td class="label"><?php echo Mage::helper('deliverydate')->__('Delivery Date')?></td>
                <td><strong><?php echo $this->formatDate($_order->getAwDeliverydateDate());?></strong></td>
            </tr>
            <?php endif;?>
            <?php if ($_order->getAwDeliverydateNotice()): ?>
            <tr>
                <td class="label"><?php echo Mage::helper('deliverydate')->__('Delivery Notice')?></td>
                <td><strong><?php echo nl2br(Mage::helper('deliverydate')->htmlEscape($_order->getAwDeliverydateNotice()));?></strong></td>
            </tr>
            <?php endif; ?>
            <tr>
                <td class="label">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
                <td>
                <?php if ($_customerUrl=$this->getCustomerViewUrl()) : ?>
                    <a href="<?php echo $_customerUrl ?>" onclick="window.open(this.href);return false;"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
                <?php else: ?>
                    <strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
                <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
                <td><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a></td>
            </tr>
            <?php if ($_groupName=$this->getCustomerGroupName()) : ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label></td>
                <td><strong><?php echo $_groupName ?></strong></td>
            </tr>
            <?php endif; ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Shipping Address-->
    <?php echo $this->getChildHtml('shipping_address') ?>
</div>
<div class="clear"></div>
