<?php if ($_products = $this->getProducts()): ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<div class="<?php echo $this->getWrapperClass() ?>">
    <h2 class="sec_header"><?php echo $this->__('Featured Products') ?></h2>
    <?php $i = 0; ?>
    <?php foreach ($_products as $_product): ?>
    <div class="grid3<?php if ($i % 4 == 0) { echo ' first'; } ?>">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(177); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
        <?php if($_product->getRatingSummary()): ?>
        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
        <?php endif; ?>
        <?php echo $this->getPriceHtml($_product, true) ?>
        <div class="actions">
            <?php if($_product->isSaleable()): ?>
                <p class="availability"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
            <?php elseif ($_product->getNoSale()): ?>
                <p class="availability no-sale"><span><?php echo $this->__('Not Available Online') ?></span></p>
            <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <ul class="add-to-links">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if ($this->helper('sendfriend')->isEnabled()): ?>
                    <li><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to Friend') ?></a></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
    <?php $i++; ?>
    <?php endforeach; ?>
    <div class="clear"></div>
</div>
<?php endif; ?>
