<div class="wdn-band wdn-text-band mrkp-maint-band">
    <div class="wdn-inner-wrapper wdn-center">
        <h1 class="clear-top">Service Temporarily Unavailable</h1>
        <p>Please excuse our mess&hellip;</p>
        <p>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.</p>
        <figure class="graphic">
            <img src="<?php echo $this->getSkinUrl() ?>images/maintenance.jpg" alt="Clay figurine dressed as a construction worker" />
        </figure>
    </div>
</div>
