<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
    <ul class="form-list checkmo-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li style="font-size: 0.8em">Please note: we will not process or ship your order until <em>complete</em> payment is received and cleared.</li>
        <?php if ($this->getMethod()->getPayableTo()): ?>
        <li>
            <label><?php echo $this->__('Make Check payable to:') ?></label>
            <?php echo $this->getMethod()->getPayableTo() ?>
        </li>
        <?php endif; ?>
        <?php if ($this->getMethod()->getMailingAddress()): ?>
        <li>
            <label><?php echo Mage::helper('payment')->__('Send Check to:') ?></label>
            <address class="checkmo-mailing-address">
                <?php echo nl2br($this->getMethod()->getMailingAddress()) ?>
            </address>
        </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
