<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <label for="po_number" class="required"><em>*</em><?php echo $this->__('Purchase Order Number') ?></label>
        <div class="input-box">
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo $this->__('Purchase Order Number') ?>" class="input-text required-entry validate-digits validate-co-length" value="<?php echo $this->htmlEscape($this->getInfoData('po_number')) ?>" />
        </div>
    </li>
</ul>
<script type="text/javascript">
Validation.add('validate-co-length', 'Please enter a valid cost object number', {minLength:10});
</script>
