<?php if (($_products = $this->getProductCollection()) && count($_products->getItems())): ?>
<?php
    $_allFeaured = $_products->getItems();
    shuffle($_allFeaured);
    $_product = current($_allFeaured);
    $_helper = $this->helper('catalog/output');
?>
<h4 style="color:#900; font-family:Georgia, 'Times New Roman', Times, serif;"><em>Featured Item</em></h4>
<div class="featured-global zenbox" style="background-color:#fffde3;">
<?php
if ($this->isSourceStoreActive($_product)) {
    $_product->setStoreId($_product->getSourceStoreView());
}
?>
    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(132); ?>" width="132" height="132" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
    <div class="product-shop">
        <h2 class="product-name sec_header"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
        <?php echo $this->getPriceHtml($_product, true) ?>
        <div class="desc std">
            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="link-more"><?php echo $this->__('Learn More') ?></a>
        </div>
    </div>
    <div class="clear"></div>
</div>
<?php endif; ?>
