<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="po_number"><?php echo Mage::helper('payment')->__('UNL Cost Object') ?> <span class="required">*</span></label><br/>
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo Mage::helper('payment')->__("UNL Cost Object") ?>" class="required-entry input-text" value="<?php echo $this->getInfoData('po_number') ?>"/>
        </div>
    </li>
</ul>