<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>

<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <span class="filter-label">
        <?php if ($_item->getCount() > 0): ?>
        <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
        <?php else: echo $_item->getLabel() ?>
        <?php endif; ?>
        </span>
        <?php if ($this->shouldDisplayProductCount()): ?>
        <span class="filter-count">(<?php echo $_item->getCount() ?>)</span>
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
