<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="zenbox primary block block-layered-nav">
    <h3><?php echo $this->__('Shop By') ?></h3>
    <?php echo $this->getStateHtml() ?>
    <?php if($this->canShowOptions()): ?>
        <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p>
        <dl id="narrow-by-list">
            <?php $_filters = $this->getFilters() ?>
            <?php foreach ($_filters as $_filter): ?>
            <?php if($_filter->getItemsCount()): ?>
                <dt><?php echo $this->__($_filter->getName()) ?></dt>
                <dd><?php echo $_filter->getHtml() ?></dd>
            <?php endif; ?>
            <?php endforeach; ?>
        </dl>
        <script type="text/javascript">decorateDataList('narrow-by-list')</script>
    <?php endif; ?>
</div>
<?php endif; ?>
