<?php /* @var $this Mage_Core_Block_Template */ ?>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="line-height: normal;">
          <tr>
               <td bgcolor="#525151" align="center">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
                         <tr>
                              <td style="padding: 20px 20px 20px 20px;">
                                   <table width="610" border="0" cellspacing="0" cellpadding="0" align="center" class="responsive-table">
                                        <tr>
                                             <td align="left" valign="middle" style="font-size: 10px; line-height: 16px; font-family: Helvetica, Arial, sans-serif; color:#cfcfcf; -webkit-text-size-adjust: none"><span class="appleFooter" style="color:#cfcfcf; -webkit-text-size-adjust: none">
                                             Unless otherwise noted, items sold by a unit or department of the University of Nebraska-Lincoln,
                                             under the management of <a href="<?php echo $this->getUrl('', array('_store' => 'default')) ?>" target="_blank" style="color:#ffffff;">UNL Marketplace</a>,
                                             are subject to sales and use taxes in the state of Nebraska in accordance with the applicable laws of the state.
                                             <a href="<?php echo $this->getUrl('', array('_direct' => 'about-us', '_store' => 'default')) ?>" target="_blank" style="color:#ffffff;" title="About UNL Marketplace">Learn more</a> about the UNL Marketplace university service.
                                             <br>
                                             <br>
                                             420 Nebraska Hall, P.O. Box 880525, Lincoln, NE 68588-0525, USA &nbsp;&nbsp;|&nbsp;&nbsp; 402-472-9964
                                             </span></td>
                                             <td width="111" valign="top" class="mobile-hide" style="padding-left:20px"><a href="http://www.unl.edu/" target="_blank" style="font-family: Arial; color: #ffffff; font-size: 14px;"><img alt="University of Nebraska-Lincoln" src="<?php echo $this->getSkinUrl('images/email/wordmark.gif') ?>" width="111" height="43" style="display: block;" border="0"></a></td>
                                        </tr>
                                   </table>
                              </td>
                         </tr>
                    </table>
               </td>
          </tr>
     </table></body>
</html>
