<?php /* @var $this Mage_Core_Block_Template */ ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><title>UNL Marketplace Email</title>

<style type="text/css">
    #outlook a{padding:0;}
	.ReadMsgBody {width: 100%;}
	.ExternalClass {width: 100%;}
	.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
	body, table, td, a{-webkit-text-size-adjust:100%; -ms-text-size-adjust:100%;}
    table, td{mso-table-lspace:0pt; mso-table-rspace:0pt;}
    img{-ms-interpolation-mode:bicubic;}
	body{margin:0; padding:0;}
    img{border:0; height:auto; line-height:100%; outline:none; text-decoration:none;}
    table{border-collapse:collapse !important;}
    body{height:100% !important; margin:0; padding:0; width:100% !important;}
	.appleBody a {color:#999999; text-decoration: none;}
	.appleFooter a {color:#ffffff;}
    .appleEvents a {color: #abadb3; font-weight:bold; text-decoration: none;}
    .appleEventsBody a {color: #81261d;; text-decoration: none;}
    blockquote .original-only, .WordSection1 .original-only {display: none !important;}
    blockquote table.forwarded-only, .WordSection1 table.forwarded-only {display: block !important;}

	@media screen and (max-width: 650px) {
		table[class="wrapper"]{
		    width:100% !important;}
		td[class="mobile-hide"]{
			display:none;}
		td[class="mobile-show"]{
			display:block!important;}
		td[class="mobile-show"] img{
		    height:auto!important;
		    width:auto!important;}
		td[class="head1"]{
			font-size: 30px!important;
			padding: 0 10px 20px!important;}
		td[class="head2"]{
			font-size: 16px!important;
			padding: 25px 20px 20px 20px!important;}
		td[class="head3"]{
			font-size: 15px!important;
			padding: 0 0 25px 0!important;}
		td[class="head4"]{
			padding: 0 20px 25px 20px !important;}
		table[class="button"]{
			width:85%!important;
			height:auto}
		td[class="button"]{
			font-size: 20px!important;
			padding: 10px!important;}
      	img[class="img-full"]{
          	width:100% !important;
          	max-width: 100%;
          	height:auto;}
		table[class="responsive-table"]{
			float: none!important;
			width:100%!important;}
		td[class="padding"]{
			padding: 10px 8% 10px 8% !important;
			text-align: center !important;}
		td[class="section-padding"]{
			padding: 50px 15px 50px 15px !important;}
	}
</style>
</head>
<body style="margin: 0; padding: 0; line-height: 0">
     <table border="0" cellpadding="0" cellspacing="0" width="100%" style="line-height: normal;">
     	  <tr>
     	      <td style="border-bottom: 1px solid #ECDEC5;">
     	          <table border="0" cellpadding="0" cellspacing="0" width="100%">
     	              <tr>
     	                  <td bgcolor="#F2EEE4" class="mobile-hide">
             	  	   		<table align="center" border="0" cellpadding="0" cellspacing="0" width="650" class="responsive-table">
                                 <tr>
                                      <td><a href="http://www.unl.edu/" target="_blank"><img src="<?php echo $this->getSkinUrl('images/email/4_0_email_01.gif') ?>" alt="" height="41" width="650" border="0" align="left" style="display: block;"></a></td>
                                 </tr>
                            </table>
                        </td>
     	              </tr>
     	              <tr>
     	                  <td bgcolor="#F8F5EC" class="mobile-hide">
     	                      <table align="center" border="0" cellpadding="0" cellspacing="0" width="650" class="responsive-table">
     	                          <tr>
     	                              <td><a href="http://www.unl.edu/" target="_blank"><img src="<?php echo $this->getSkinUrl('images/email/4_0_email_02.gif') ?>" alt="" height="30" width="650" border="0" align="left" style="display: block;"></a></td>
     	                          </tr>
     	                          <tr>
     	                              <td align="center" style="font-size: 30px; line-height: 1.5; font-family: Georgia, serif;"><a href="<?php echo $this->getUrl('', array('_store' => 'default')) ?>" target="_blank" style="text-decoration: none; color:#444341"><img src="<?php echo $this->getSkinUrl('images/email/4_0_email_03.gif') ?>" width="650" height="48" alt="UNL Marketplace" border="0" align="left" style="display: block;"></a></td>
     	                          </tr>
     	                      </table>
 	                      </td>
     	              </tr>
     	              <tr>
     	                  <td bgcolor="#F8F5EC" style="display: none;" class="mobile-show">
     	                      <table align="center" border="0" cellpadding="0" cellspacing="0" width="650" class="responsive-table">
     	                          <tr>
     	                              <td rowspan="2" width="54"><a href="http://www.unl.edu/" target="_blank"><img src="<?php echo $this->getSkinUrl('images/email/4_0_email_05.gif') ?>" width="1" height="1" alt="" border="0" align="left" style="display: block; width: 0; height: 0;"></a></td>
     	                              <td><img src="<?php echo $this->getSkinUrl('images/email/4_0_email_06.gif') ?>" width="1" height="1" alt="" border="0" align="left" style="display: block; width: 0; height: 0;"></td>
     	                          </tr>
     	                          <tr>
     	                              <td class="mobile-header" style="font-size: 0px; line-height: 0; font-family: Georgia, serif;"><a href="<?php echo $this->getUrl('') ?>" target="_blank" style="text-decoration: none; color: #444341;"><img src="<?php echo $this->getSkinUrl('images/email/4_0_email_08.gif') ?>" width="1" height="1" alt="" border="0" align="left" style="display: block; height: 0;"></a></td>
     	                          </tr>
     	                      </table>
     	                  </td>
     	              </tr>
     	          </table>
     	      </td>
     	  </tr>
     </table>
