<?php echo $this->getMethod()->getTitle() ?>
    {{pdf_row_separator}}
<?php if($this->getInfo()->getAdditionalData()): ?>
    {{pdf_row_separator}}
    <?php if($this->getPayableTo()): ?>
        <?php echo Mage::helper('payment')->__('Make Check payable to: %s', $this->htmlEscape($this->getPayableTo())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
    <?php if($this->getMailingAddress()): ?>
        <?php echo Mage::helper('payment')->__('Send Check to:') ?>
        {{pdf_row_separator}}
        <?php echo str_replace('\n', '{{pdf_row_separator}}', $this->htmlEscape($this->getMailingAddress())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
<?php endif; ?>
