<?php /* @var $this Unl_Core_Block_Payment_Info_Invoicelater */ ?>
<?php echo $this->getMethod()->getTitle() ?>
    {{pdf_row_separator}}
<?php if($this->getInfo()->getAdditionalData()): ?>
    {{pdf_row_separator}}
    <?php if($this->getRemitTo()): ?>
        <?php echo Mage::helper('unl_core')->__('Remit to:') ?>
        {{pdf_row_separator}}
        <?php echo nl2br($this->htmlEscape($this->getRemitTo())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
<?php endif; ?>
