<?php /* @var $this Unl_Core_Block_Payment_Info_Invoicelater */ ?>
<?php echo $this->getMethod()->getTitle() ?>
<?php if($this->getShowTotals() && $this->getInfo()->getAdditionalData()): ?>
    {{pdf_row_separator}}
    <?php if($this->getRemitTo()): ?>
        <?php echo Mage::helper('unl_core')->__('Remit to:') ?>
        {{pdf_row_separator}}
        <?php echo str_replace(array("\r", "\n"), '{{pdf_row_separator}}', $this->stripTags($this->getRemitTo())) ?>
    <?php endif; ?>
<?php endif; ?>
{{pdf_row_separator}}
