<?php /* @var $this AW_Deliverydate_Block_Html_Date */
$Days = $this->getUnavailDays();
$first_day = $this->getFirstAvailableDate()->toArray();
?>
<div class="input-box input-group">
    <input type="text" name="<?php echo $this->getName() ?>" id="<?php echo $this->getId() ?>" value="<?php echo $this->getValue() ?>" class="<?php echo $this->getClass() ?>" <?php echo $this->getExtraParams() ?>/>
    <span class="input-group-btn"><button type="button" class="button" title="<?php echo $this->helper('core')->__('Select Date') ?>"><span><span><i class="mrkp-icon-calendar-empty"></i></span></span></button></span>
</div>
<script type="text/javascript">
	WDN.initializePlugin('jqueryui', [function(){
		var $ = require('jquery'),
	        AW_DD_Days = <?php echo $this->getDaysJson($Days->getDays()) ?>,
		    AW_DD_RWeekdays = <?php echo $this->getRecurrentWeekdaysJson($Days->getRecurrentWeekdays()) ?>,
		    AW_DD_RDays = <?php echo $this->getRecurrentDaysJson($Days->getRecurrentDays()) ?>,
			$trigger = $("#<?php echo $this->getId() ?>");

		$trigger.datepicker({
            minDate         : new Date(<?php echo $first_day['year'] ?>, <?php echo ($first_day['month']-1) ?>, <?php echo $first_day['day'] ?>),
			beforeShowDay   : function(D){
				if(
					(AW_DD_RDays.indexOf(D.getDate()) != -1) ||
					(AW_DD_RWeekdays.indexOf(D.getDay()) != -1) ||
					(AW_DD_Days.indexOf(D.getFullYear()+"-"+(D.getMonth()+1)+"-"+D.getDate()) != -1)){

					return [false];
				}
				return [true];
			}
        });

        $trigger.find('~ * button').click(function() {
            $trigger.datepicker('show');
        });
    }]);
</script>
