<?php if (($_products = $this->getProductCollection()) && count($_products->getItems())): ?>
<?php 
    $_allFeaured = $_products->getItems();
    shuffle($_allFeaured);
    $_product = current($_allFeaured);
    $_helper = $this->helper('catalog/output'); 
?>
<div class="featured zenbox">
    <h2 class="sec_main"><?php echo $this->__('Featured Product') ?></h2>
    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(174, 174); ?>" width="174" height="174" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
    <div class="product-shop">
        <h2 class="sec_header"><?php echo $_helper->productAttribute($_product, $this->htmlEscape($_product->getName()), 'name') ?></h2>
        
        <div class="right-box">
            <?php echo $this->getPriceHtml($_product, true) ?>
            <p><button class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button></p>
            <p class="add-to">
                Add to: 
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Wishlist') ?></a>
                <?php endif; ?>
                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    <span class="separator">|</span> <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Compare') ?></a>
                <?php endif; ?>
            </p>
        </div>
        
        <?php if($_product->getRatingSummary()): ?>
        <?php echo $this->getReviewsSummaryHtml($_product) ?>
        <?php endif; ?>
        
        <div class="desc std">
            <?php echo nl2br($_product->getShortDescription()) ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->__('Learn More') ?></a>
        </div>
    </div>
    <div class="clear"></div>
</div>
<?php endif; ?>