<div class="zenbox cool block block-subscribe">
    <h3>UNL Marketplace <?php echo $this->__('Newsletter') ?></h3>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
            <div class="input-box">
               <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Enter an e-mail address') ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
