<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<a class="mrkp-offset-anchor" id="category_main"></a>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss icon-link" title="<?php echo $this->__('Subscribe to RSS Feed') ?>"></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php $hasHtml = strpos($_description, '<') !== false; ?>
        <?php if (!$hasHtml): ?>
        <div>
        <?php endif; ?>
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
        <?php if (!$hasHtml): ?>
        </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>

<?php if($this->isContentMode()): ?>
    <div class="std"><?php echo $this->getCmsBlockHtml() ?></div>

<?php elseif($this->isMixedMode()): ?>
    <div class="std"><?php echo $this->getCmsBlockHtml() ?></div>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
