<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Mage::helper('adminhtml')->__('Log into Magento Admin Page') ?> / UNL Marketplace</title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('boxes.css') ?>" media="all" />
    <link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />

    <style type="text/css">
    h2 { text-align: center; }#unl-login {text-align: center;}#unl-login a {text-decoration: none;display: inline-block;padding: 1em 4em;background:#d00000;border-style:outset;border-color:#a00000}#unl-login a:hover {color: #fff;}
    </style>

    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/captcha.js') ?>"></script>

    <!--[if IE]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('iestyles.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('below_ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
</head>
<body id="page-login">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="" id="loginForm">
                <div class="login-form">
                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                    <h2><?php echo Mage::helper('adminhtml')->__('Log in to Admin Panel') ?></h2>
                    <div id="messages">
                        <?php echo $this->getMessagesBlock()->toHtml() ?>
                    </div>
                    <div id="std-login" class="no-display">
                    <div class="input-box input-left"><label for="username"><?php echo Mage::helper('adminhtml')->__('User Name:') ?></label><br/>
                        <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" /></div>
                    <div class="input-box input-right"><label for="login"><?php echo Mage::helper('adminhtml')->__('Password:') ?></label><br />
                        <input type="password" id="login" name="login[password]" class="required-entry input-text" value="" /></div>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <div class="clear"></div>
                    <div class="form-buttons">
                        <a class="left" href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/index/forgotpassword', array('_nosecret' => true)) ?>"><?php echo Mage::helper('adminhtml')->__('Forgot your password?') ?></a>
                        <input type="submit" class="form-button" value="<?php echo Mage::helper('adminhtml')->__('Login') ?>" title="<?php echo Mage::helper('adminhtml')->__('Login') ?>" /></div>
                    </div>
                    <div id="unl-login">
                        <h3>UNL Marketplace Authorized Users</h3>
                        <p>Your university credentials are used to access this service.</p>
                    	<a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/cas/logincas', array('_nosecret' => true)) ?>" class="form-button"><?php echo Mage::helper('adminhtml')->__('UNL Login') ?></a>
                    </div>
                </div>
                <p class="legal"><?php echo Mage::helper('adminhtml')->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')) ?></p>
            </form>
            <div class="bottom"></div>
            <script type="text/javascript">
                 var loginForm = new varienForm('loginForm');
                 $$('.login-container')[0].observe('click', function(e) {
                     if (e.target == this) {
                         $('unl-login').toggleClassName('no-display');
                         $('std-login').toggleClassName('no-display');
                     }
                 });
            </script>
        </div>
    </div>
</body>
</html>

