<?php if ($_item = $this->getItem()): ?>
    <h5 class="title"><?php echo $this->htmlEscape($_item->getName()) ?></h5>
    <div><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->htmlEscape($this->getSku()))); ?></div>
    <?php if ($_item->getChildrenItems()): ?>
		<?php
		$selections = array();
		foreach ($_item->getChildrenItems() as $_child) {
			$options = $_child->getProductOptions();
			$attributes = unserialize($options['bundle_selection_attributes']);
			if (!isset($selections[$attributes['option_id']])) {
			    $selections[$attributes['option_id']] = array(
			        'label' => $attributes['option_label'],
			        'selections' => array()
			    );
			}
			$selections[$attributes['option_id']]['selections'][] = sprintf('%d', $attributes['qty']) . ' x ' . $_child->getName();
		}
		ksort($selections);
		?>
    	<dl class="item-options">
    	<?php foreach ($selections as $option): ?>
			<dt><?php echo $option['label'] ?></dt>
			<?php foreach ($option['selections'] as $selection): ?>
				<dd><?php echo $selection ?></dd>
			<?php endforeach; ?>
		<?php endforeach; ?>
    	</dl>
	<?php endif; ?>
    <?php if ($this->getOrderOptions()): ?>
        <dl class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <dt><?php echo $_option['label'] ?></dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                <?php echo $this->getCustomizedOptionValue($_option); ?>
            <?php else: ?>
                <?php echo Mage::helper('core/string')->truncate($_option['value'], 55, '', $_remainder);?>
                <?php if ($_remainder):?>
                    ... <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_remainder ?></span>
                    <script type="text/javascript">
                    $('<?php echo $_id ?>').hide();
                    $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
                    $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});
                    </script>
                <?php endif;?>
            <?php endif;?>
            </dd>
        <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php echo $this->htmlEscape($_item->getDescription()) ?>
<?php endif; ?>