<?php  $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title title-buttons">
    <div class="links">
        <?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
            <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="link-rss"><?php echo $this->__('Subscribe to Order Status') ?></a>
            <span class="separator">|</span>
        <?php endif; ?>
        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
            <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
            <span class="separator">|</span>
        <?php endif ?>
        <a href="<?php echo $this->getPrintUrl($_order) ?>" class="link-print" onclick="this.target='_blank';"><?php echo $this->__('Print Order') ?></a>
    </div>
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul class="wdn_tabs disableSwitching">
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="selected"><a><?php echo $_link->getLabel() ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Address') ?></h2>
            </div>
            <div class="box-content">
            <?php if (Mage::helper('unl_core/shipping_pickup')->isMethodPickup($_order->getShippingMethod())): ?>
                <?php echo $this->__('Pickup order') ?>
            <?php else: ?>
                <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
            <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Method') ?><?php /* | <a href="#"><?php echo $this->__('Track Order') ?></a>*/ ?></h2>
            </div>
            <div class="box-content">
                <?php if ($_order->getShippingDescription()): ?>
                    <?php echo $_order->getShippingDescription() ?>
                <?php else: ?>
                    <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                <?php endif; ?>

                <?php if (Mage::helper('unl_core/shipping_pickup')->isMethodPickup($_order->getShippingMethod())): ?>
                    <?php $_pickupStore = current($_order->getAllVisibleItems())->getSourceStoreView(); ?>
                    <p><strong><?php echo $this->__('Pickup Location:') ?></strong><br />
                    <?php echo nl2br(Mage::helper('unl_core/shipping_pickup')->getPickupLocation($_order->getShippingMethod(), $_pickupStore)) ?></p>
                <?php endif; ?>

                <?php if ($_order->getAwDeliverydateDate()): ?>
                <br/>
                <strong><?php echo Mage::helper('deliverydate')->__('Delivery Date')?></strong>
                &nbsp;
                <?php echo $this->formatDate($_order->getAwDeliverydateDate());?>
                <?php endif; ?>

                <?php if ($_order->getAwDeliverydateNotice()): ?>
                <br/>
                <strong><?php echo Mage::helper('deliverydate')->__('Delivery Notice')?></strong><br/>
                &nbsp;
                <?php echo $_order->getAwDeliverydateNotice();?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
