<?php /* @var $this Mage_Reports_Block_Product_Viewed */ ?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="zenbox neutral block block-viewed">
    <h3><?php echo $this->__('Recently Viewed Products') ?></h3>
    <ol id="recently-viewed-items">
    <?php foreach ($_products as $_item): ?>
        <li class="item">
            <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('recently-viewed-items');</script>
</div>
<?php endif; ?>
