<?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/metanfavico_html5.html'); ?>
<!--
    Membership and regular participation in the UNL Web Developer Network
    is required to use the UNL templates. Visit the WDN site at
    http://wdn.unl.edu/. Click the WDN Registry link to log in and
    register your unl.edu site.
    All UNL template code is the property of the UNL Web Developer Network.
    The code seen in a source code view is not, and may not be used as, a
    template. You may not use this code, a reverse-engineered version of
    this code, or its associated visual presentation in whole or in part to
    create a derivative work.
    This message may not be removed from any pages based on the UNL site template.

    $Id: php.mobile.dwt.php 536 2009-07-23 15:47:30Z bbieber2 $
-->
<meta name="viewport" content="initial-scale=1.0, width=device-width" />
<link rel="stylesheet" type="text/css" media="screen" href="/wdn/templates_3.0/css/mobile.css" />
<script type="text/javascript" src="/wdn/templates_3.0/scripts/mobile.js"></script>
<?php Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/browserspecifics_html5.html'); ?>
<!-- TemplateBeginEditable name="doctitle" -->
<title>
<?php if (substr($this->getTitle(), 0, 3) == 'UNL'): ?>
    <?php echo $this->getTitle() ?>
<?php else: ?>
    UNL | Marketplace<?php if (Mage::app()->getStore()->getCode() != 'default'): ?> | <?php echo $this->htmlEscape(Mage::app()->getGroup()->getName()) ?><?php endif; ?> | <?php echo $this->getTitle() ?>
<?php endif; ?>
</title>
<!-- TemplateEndEditable --><!-- TemplateBeginEditable name="head" -->
<!-- Place optional header elements here -->
<link rel="home" href="<?php echo $this->getBaseUrl() ?>" />
<?php if (Mage::helper('unl_cas')->getAuth()->isLoggedIn()): ?>
<link rel="logout" href="<?php echo $this->getUrl('customer/account/logout') ?>" />
<?php endif; ?>
<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
</script>

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<!-- TemplateEndEditable -->
