<?php $_cartItems = $this->helper('checkout/cart')->getSummaryCount(); ?>
<?php $_cartUrl = $this->getUrl('checkout/cart'); ?>
<div class="subnav menu-wrapper">
    <dl id="menu">
        <dt class="menu dropdown"><a href="#">Menu</a></dt>
        <dd class="menu-box">
            <?php echo $this->getChildHtml('topLinks') ?>
            <?php echo $this->getChildHtml('checkoutLinks') ?>
            <?php echo $this->getChildHtml('accountLinks') ?>
        </dd>
        <dt class="cart-icon <?php echo in_array('checkout_cart_index', $this->getLayout()->getUpdate()->getHandles()) ? 'active' : '' ?>">
            <a href="<?php echo $_cartUrl ?>">Cart<?php echo $_cartItems > 0 ? '<span>'.$_cartItems.'</span>' : ''; ?></a>
        </dt>
        <dd></dd>
    </dl>
    <div class="search">
        <?php echo $this->getChildHtml('topSearch') ?>
    </div>
</div>
<?php echo $this->getChildHtml('topCart') ?>
