<?php $_order = $this->getOrder() ?>
<?php
$orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true);
$orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true);
?>
<div class="box-left">
    <!--Order Information-->
    <div class="entry-edit">
        <?php if ($_order->getEmailSent()):
            $_email=$this->__('Order confirmation email sent');
        else:
            $_email=$this->__('Order confirmation email not sent');
        endif; ?>
        <div class="entry-edit-head">
        <?php if ($this->getNoUseOrderLink()): ?>
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?> (<?php echo $_email ?>)</h4>
        <?php else: ?>
            <a href="<?php echo $this->getViewUrl($_order->getId()) ?>"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?></a>
            <strong>(<?php echo $_email ?>)</strong>
        <?php endif; ?>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
                <td><strong><?php echo $orderAdminDate ?></strong></td>
            </tr>
            <?php if ($orderAdminDate != $orderStoreDate):?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label></td>
                <td><strong><?php echo $orderStoreDate ?></strong></td>
            </tr>
            <?php endif;?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
                <td><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
                <td><strong><?php echo $this->getOrderStoreName() ?></strong></td>
            </tr>
            <?php if($_order->getRelationChildId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the new order') ?></label></td>
                <td><a href="<?php echo $this->getViewUrl($_order->getRelationChildId()) ?>">
                    <?php echo $_order->getRelationChildRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRelationParentId()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Link to the previous order') ?></label></td>
                <td><a href="<?php echo $this->getViewUrl($_order->getRelationParentId()) ?>">
                    <?php echo $_order->getRelationParentRealId() ?>
                </a></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getRemoteIp()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Placed from IP') ?></label></td>
                <td><strong><?php echo $_order->getRemoteIp(); echo ($_order->getXForwardedFor())?' (' . $_order->getXForwardedFor() . ')':''; ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            <?php if($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
                <td><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
            </tr>
            <?php endif; ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('External #') ?></label></td>
                <td>
                    <div id="external_id" class="giftmessage-single-item">
                        <strong class="value"><?php echo $this->htmlEscape($_order->getExternalId()) ?></strong>
                        <?php if ($this->getNoUseOrderLink()): ?>
                        <div class="action-link-holder">
                            <a class="action-link" href="#" onclick="return toggleExternalId()">
                                <span class="default-text">
                                    <span class="add"<?php if($_order->getExternalId()): ?> style="display:none;"<?php endif;?>><?php echo $this->helper('sales')->__('Add External ID') ?></span>
                                    <span class="edit"<?php if(!$_order->getExternalId()): ?> style="display:none;"<?php endif;?>><?php echo $this->helper('sales')->__('Edit External ID') ?></span>
                                </span>
                                <span class="close-text" style="display:none;"><?php echo $this->helper('sales')->__('Save External ID') ?></span>
                            </a>
                        </div>
                        <div class="external-id-form" id="external_id_edit" style="display:none;">
                            <form id="external_id_form" action="<?php echo $this->getUrl('unl/sales_order_view_externalid/save', array('order_id' => $_order->getId())) ?>">
                                <div class="entry-edit">
                                    <fieldset>
                                        <span class="field-row">
                                            <input class="input-text" type="text" id="external_id_value" name="external_id" value="<?php echo $this->htmlEscape($_order->getExternalId()) ?>" />
                                        </span>
                                    </fieldset>
                                </div>
                            </form>
                        </div>
                        <?php endif; ?>
                    </div>
                    <?php if ($this->getNoUseOrderLink()): ?>
                    <script type="text/javascript">
                    function toggleExternalId() {
                        var container = $('external_id');

                        if (!$('external_id_form').isListening) {
                            $('external_id_form').isListening = true;
                            $('external_id_form').onsubmit = function() { return false; };
                        }
                        
                        if (!container.toggleExternal) {
                            container.toggleExternal = true;

                            $('external_id_edit').show();
                            container.down('.action-link').addClassName('open');
                            container.down('.default-text').hide();
                            container.down('.close-text').show();
                            container.down('.value').update($('external_id_value').value);
                        } else {
                        	container.toggleExternal = false;

                        	new Ajax.Request($('external_id_form').action, {
                        	    parameters: Form.serialize($('external_id_form'), true),
                        	    loaderArea: 'external_id',
                        	    onComplete: function(transport) {
                        		    container.down('.action-link').removeClassName('open');
                        		    container.down('.default-text').show();
                        		    container.down('.close-text').hide();
                        		    container.down('.value').update($('external_id_value').value);
                        		    $('external_id_edit').hide();
                        		    if (transport.responseText.match(/YES/g)) {
                        		    	container.down('.default-text').down('.edit').show();
                                        container.down('.default-text').down('.add').hide();
                        		    } else {
                            		    container.down('.default-text').down('.add').show();
                            		    container.down('.default-text').down('.edit').hide();
                        		    }
                        		}
                        	});
                        }
                        return false;
                    }
                    </script>
                    <?php endif; ?>
                </td>
            </tr>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Account Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('sales')->__('Account Information') ?></h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
                    <td>
                    <?php if ($_customerUrl=$this->getCustomerViewUrl()) : ?>
                        <a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
                    <?php else: ?>
                        <strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
                    <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
                    <td><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a></td>
                </tr>
                <?php if ($_groupName=$this->getCustomerGroupName()) : ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label></td>
                    <td><strong><?php echo $_groupName ?></strong></td>
                </tr>
                <?php endif; ?>
                <?php if ($_dob=$this->getOrder()->getCustomerDob()) : ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Date of Birth') ?></label></td>
                    <td><strong><?php echo Mage::helper('core')->formatDate($_dob, 'medium') ?></strong></td>
                </tr>
                <?php endif; ?>
                <?php if ($_taxvat = $_order->getCustomerTaxvat()):?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('TAX/VAT Number') ?></label></td>
                    <td><strong><?php echo $this->htmlEscape($_taxvat)?></strong></td>
                </tr>
                <?php endif;?>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>

<div class="box-left">
    <!--Billing Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-billing-address"><?php echo Mage::helper('sales')->__('Billing Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_order->getBillingAddress()->getFormated(true) ?></address>
        </fieldset>
    </div>
</div>
<?php if (!$this->getOrder()->getIsVirtual()): ?>
<div class="box-right">
    <!--Shipping Address-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
        </div>
        <fieldset>
            <address><?php echo $_order->getShippingAddress()->getFormated(true) ?></address>
        </fieldset>
    </div>
</div>
<div class="clear"></div>
<?php endif; ?>
