<div class="wdn-grid-set mrkp-well">
    <div class="bp2-wdn-col-one-fourth mrkp-well-up">
        <h2 class="mrkp-well-heading"><?php echo $this->__('Orders') ?></h2>
        <p class="mrkp-well-desc"><?php echo $this->__('View recent orders') ?></p>
    </div>
    <span class="mrkp-well-sep-abs-one-fourth"></span>
    <div class="bp2-wdn-col-three-fourths">
        <div class="wdn-grid-set bp1-wdn-grid-set-halves">
            <div class="wdn-col">
                <ul class="mrkp-list-flat">
            	   <li><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('Your Orders') ?></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
