<?php

/* @var $this Mage_Eav_Model_Entity_Setup */
$installer = $this;

$installer->startSetup();

$installer->run("

/* Table Stucture for table `unl_tax_boundary` */

-- DROP TABLE IF EXISTS {$this->getTable('unl_tax_boundary')};
CREATE TABLE `unl_tax_boundary` (
  `record_type` char(1) NOT NULL,
  `begin_date` date NOT NULL,
  `end_date` date NOT NULL,
  `low_address_range` int(10) unsigned default NULL,
  `high_address_range` int(10) unsigned default NULL,
  `odd_even_indicator` char(1) default NULL,
  `street_pre_directional` varchar(2) default NULL,
  `street_name` varchar(20) default NULL,
  `street_suffix_abbr` varchar(4) default NULL,
  `street_post_directional` varchar(2) default NULL,
  `address_secondary_abbr` varchar(4) default NULL,
  `address_secondary_low` varchar(8) default NULL,
  `address_secondary_high` varchar(8) default NULL,
  `address_secondary_odd_even` char(1) default NULL,
  `city_name` varchar(28) default NULL,
  `zip_code` int(5) unsigned default NULL,
  `plus_4` int(4) unsigned zerofill default NULL,
  `zip_code_low` int(5) unsigned default NULL,
  `zip_ext_low` int(4) unsigned zerofill default NULL,
  `zip_code_high` int(5) unsigned default NULL,
  `zip_ext_high` int(4) unsigned zerofill default NULL,
  `composite_ser_code` char(5) default NULL,
  `fips_state_code` char(2) default NULL,
  `fips_state_indicator` char(2) default NULL,
  `fips_county_code` char(3) default NULL,
  `fips_place_number` char(5) default NULL,
  `fips_place_class_code` char(2) default NULL,
  `longitude` decimal(10,7) default NULL,
  `latitude` decimal(10,7) default NULL,
  `special_tax_district_code_src_1` char(2) default NULL,
  `special_tax_district_code_1` char(5) default NULL,
  `tax_auth_type_code_1` char(2) default NULL,
  `special_tax_district_code_src_2` char(2) default NULL,
  `special_tax_district_code_2` char(5) default NULL,
  `tax_auth_type_code_2` char(2) default NULL,
  `special_tax_district_code_src_3` char(2) default NULL,
  `special_tax_district_code_3` char(5) default NULL,
  `tax_auth_type_code_3` char(2) default NULL,
  `special_tax_district_code_src_4` char(2) default NULL,
  `special_tax_district_code_4` char(5) default NULL,
  `tax_auth_type_code_4` char(2) default NULL,
  `special_tax_district_code_src_5` char(2) default NULL,
  `special_tax_district_code_5` char(5) default NULL,
  `tax_auth_type_code_5` char(2) default NULL,
  `special_tax_district_code_src_6` char(2) default NULL,
  `special_tax_district_code_6` char(5) default NULL,
  `tax_auth_type_code_6` char(2) default NULL,
  `special_tax_district_code_src_7` char(2) default NULL,
  `special_tax_district_code_7` char(5) default NULL,
  `tax_auth_type_code_7` char(2) default NULL,
  `special_tax_district_code_src_8` char(2) default NULL,
  `special_tax_district_code_8` char(5) default NULL,
  `tax_auth_type_code_8` char(2) default NULL,
  `special_tax_district_code_src_9` char(2) default NULL,
  `special_tax_district_code_9` char(5) default NULL,
  `tax_auth_type_code_9` char(2) default NULL,
  `special_tax_district_code_src_10` char(2) default NULL,
  `special_tax_district_code_10` char(5) default NULL,
  `tax_auth_type_code_10` char(2) default NULL,
  `special_tax_district_code_src_11` char(2) default NULL,
  `special_tax_district_code_11` char(5) default NULL,
  `tax_auth_type_code_11` char(2) default NULL,
  `special_tax_district_code_src_12` char(2) default NULL,
  `special_tax_district_code_12` char(5) default NULL,
  `tax_auth_type_code_12` char(2) default NULL,
  `special_tax_district_code_src_13` char(2) default NULL,
  `special_tax_district_code_13` char(5) default NULL,
  `tax_auth_type_code_13` char(2) default NULL,
  `special_tax_district_code_src_14` char(2) default NULL,
  `special_tax_district_code_14` char(5) default NULL,
  `tax_auth_type_code_14` char(2) default NULL,
  `special_tax_district_code_src_15` char(2) default NULL,
  `special_tax_district_code_15` char(5) default NULL,
  `tax_auth_type_code_15` char(2) default NULL,
  `special_tax_district_code_src_16` char(2) default NULL,
  `special_tax_district_code_16` char(5) default NULL,
  `tax_auth_type_code_16` char(2) default NULL,
  `special_tax_district_code_src_17` char(2) default NULL,
  `special_tax_district_code_17` char(5) default NULL,
  `tax_auth_type_code_17` char(2) default NULL,
  `special_tax_district_code_src_18` char(2) default NULL,
  `special_tax_district_code_18` char(5) default NULL,
  `tax_auth_type_code_18` char(2) default NULL,
  `special_tax_district_code_src_19` char(2) default NULL,
  `special_tax_district_code_19` char(5) default NULL,
  `tax_auth_type_code_19` char(2) default NULL,
  `special_tax_district_code_src_20` char(2) default NULL,
  `special_tax_district_code_20` char(5) default NULL,
  `tax_auth_type_code_20` char(2) default NULL,
  `boundary_id` int(11) NOT NULL auto_increment,
  PRIMARY KEY  (`boundary_id`),
  KEY `IX_BOUNDARY_RECORD_TYPE` (`record_type`),
  KEY `IX_BOUNDARY_CITY_STREET` (`city_name`,`street_name`),
  KEY `IX_BOUNDARY_ZIP_STREET_NAME` (`zip_code`,`street_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

");

$installer->endSetup();
