<?php
/**
 * Uploader template for Wysiwyg Images
 *
 * @see Unl_Core_Block_Adminhtml_Cms_Wysiwyg_Images_Content_Uploader
 */
?>
<div id="<?php echo $this->getHtmlId() ?>" class="uploader">
    <div class="buttons">
        <?php echo $this->getBrowseButtonHtml() ?>
        <?php echo $this->getUploadButtonHtml() ?>
    </div>
    <div class="clear"></div>
    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
        <div id="{{id}}" class="file-row">
        <span class="file-info">{{name}} ({{size}})</span>
        <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
        <span class="progress-text"></span>
        <div class="clear"></div>
        </div>
    </div>
    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template-progress">
        {{percent}}% {{uploaded}} / {{total}}
    </div>
</div>

<script type="text/javascript">
//<![CDATA[

<?php echo $this->getJsObjectName() ?> = new Pluploader('<?php echo $this->getHtmlId() ?>', <?php echo $this->getConfigJson() ?>);
<?php echo $this->getJsObjectName() ?>.onFilesComplete = function(completedFiles){
    completedFiles.each(function(file){
        <?php echo $this->getJsObjectName() ?>.removeFile(file.id);
    });
    MediabrowserInstance.handleUploadComplete();
}
</script>
