<div class="page-title">
   <h1><?php echo Mage::helper('sales')->__('Returns') ?></h1>
</div>
<div class="block-content">
   <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
       <div class="fieldset">
       <p><?php echo Mage::helper('sales')->__('Enter the billing last name and email address or zip/postal code of the order billing address for the provided order #.') ?></p>
       <ul class="form-list">
           <li class="fields">
               <div class="field">
                   <label for="oar_order_id" class="required"><em>*</em> <?php echo Mage::helper('sales')->__('Order #') ?></label>
                   <div class="input-box">
                       <input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id"/>
                   </div>
               </div>
               <div class="field">
                   <label for="oar_billing_lastname" class="required"><em>*</em> <?php echo Mage::helper('sales')->__('Billing Last Name') ?></label>
                   <div class="input-box">
                       <input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname" />
                   </div>
               </div>
           </li>
           <li>
               <label for="quick_search_type_id" class="required"><em>*</em> <?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
               <div class="input-box">
                   <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                       <option value="email"><?php echo Mage::helper('sales')->__('Email Address') ?></option>
                       <option value="zip"><?php echo Mage::helper('sales')->__('Zip/Postal Code') ?></option>
                   </select>
               </div>
           </li>
           <li id="oar-email">
               <label for="oar_email" class="required"><em>*</em> <?php echo Mage::helper('sales')->__('Email Address') ?></label>
               <div class="input-box">
                   <input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email" />
               </div>
           </li>
           <li id="oar-zip">
               <label for="oar_zip" class="required"><em>*</em> <?php echo Mage::helper('sales')->__('Billing Zip/Postal Code') ?></label>
               <div class="input-box">
                   <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip"/>
               </div>
           </li>
       </ul>
       </div>
       <div class="buttons-set">
           <p class="required">* Required Fields</p>
           <button type="submit" title="Continue" class="button"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
       </div>
   </form>
</div>
<script type="text/javascript">
//<![CDATA[
   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
   showIdentifyBlock($('quick_search_type_id').value);
//]]>
</script>
