<?php /* @var $this Mage_Catalog_Block_Layer_View */
?>
<?php if($this->canShowBlock()): ?>
<div class="wdn-band wdn-light-complement-band block block-layered-nav">
    <div class="wdn-inner-wrapper wdn-inner-padding-sm">
    <nav role="navigation" class="skipnav">
        <a href="#category_main">Skip filters</a>
    </nav>
    <div class="block-title">
        <strong><span><?php echo $this->__('Narrow your choices') ?></span></strong>
    </div>
    <div class="block-content">
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <p class="block-subtitle"><?php echo $this->__('Available filters') ?> <a href="#"><i class="toggle-link"></i><span class="wdn-text-hidden">Toggle display</span></a></p>
            <ul class="wdn-grid-set-halves bp1-wdn-grid-set-fourths no-js-show" id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount() > 1): ?>
                    <li class="wdn-col">
                        <strong><?php echo $this->__($_filter->getName()) ?></strong>
                        <div><?php echo $_filter->getHtml() ?></div>
                    </li>
                <?php endif; ?>
                <?php endforeach; ?>
            </ul>
            <script type="text/javascript">
            decorateDataList('narrow-by-list');
            require(['jquery'], function($) {
                $('.block-layered-nav .toggle-link').click(function(e) {
                    e.preventDefault();
                    $(this).toggleClass('expanded');
                    $('#narrow-by-list').toggle();
                });
            });
            </script>
        <?php endif; ?>
    </div>
    </div>
</div>
<?php endif; ?>
