<?php if ($this->displayNotice()): ?>
<div class="no-display wdn_notice <?php echo $this->getNoticeType() ?>">
    <div class="close"><a title="Close this notice" href="#">Close this notice</a></div>
    <div class="message">
        <div class="title"><?php echo $this->escapeHtml($this->getNoticeTitle()) ?></div>
        <p><?php echo nl2br($this->escapeHtml($this->getNotice())) ?></p>
    </div>
</div>
<script type="text/javascript">
require(['jquery', 'wdn'], function($, WDN) {
	WDN.loadCSS(WDN.getTemplateFilePath('css/modules/notices.css'));
	$(function() {
    	if (!WDN.getCookie('mkpl_ack')) {
    		$('.wdn_notice').removeClass('no-display');
    	}

    	$('.wdn_notice .close').click(function() {
    	    $(this).closest('.wdn_notice').slideUp("slow", function() {
    	        $(this).remove();
    	    });
    	    var date = new Date();
    	    var days = 7;
    	    date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
    	    document.cookie = "mkpl_ack=1;expires=" + date.toUTCString() + ";path=/";
    	    return false;
    	});
	});
});
</script>
<?php endif; ?>
