<div class="search-suggestion zenbox">
    <h2>Are you looking for informational pages?</h2>
    <p>The following results are only from our product database. If you'd like to search for information/pages related to this store, please use the red search box at the top of the page or do a <a href="http://www1.unl.edu/search/?u=<?php echo urlencode(Mage::getBaseUrl()) ?>&amp;q=<?php echo urlencode(Mage::helper('catalogsearch')->getQueryText()) ?>">web search now</a>.</p>
</div>
