<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('My Dashboard') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if (Mage::helper('unl_cas')->canShowCasLinkNotice()): ?>
    <div class="box box-unl-cas-link">
        <div class="box-title">
            <h3><?php echo $this->__('Are you a UNL Student, Faculty, or Staff?') ?></h3>
            <a href="#"><?php echo $this->__('Hide') ?></a>
        </div>
        <div class="box-content">
            <p><?php echo $this->__('Link your UNL account to your shopping account to gain access to many of the products and features only available to members of the UNL community.') ?></p>
            <div class="actions">
                <button class="button" onclick="setLocation('<?php echo $this->getUrl('unl_cas/account/caslink') ?>')"><span><span><?php echo $this->__('Link UNL Account') ?></span></span></button>
            </div>
        </div>
    </div>
    <script type="text/javascript">
    $$('.box-unl-cas-link a').each(function(element){
        Event.observe(element, 'click', function(event){
        	var request = new Ajax.Request(
                '<?php echo $this->getUrl('unl_cas/account/ignoreLink') ?>',
                {method: 'post'}
            );
            $$('.box-unl-cas-link')[0].hide();
            Event.stop(event);
        });
    });
    </script>
    <?php endif; ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="box-account box-info">
        <div class="box-head">
            <h2><?php echo $this->__('Account Information') ?></h2>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.extra') ?>
        <?php echo $this->getChildHtml('info') ?>
        <?php echo $this->getChildHtml('address') ?>
    </div>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
