<?php /* @var $this Mage_Wishlist_Block_Customer_Sidebar */ ?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
<div class="hover-menu block block-wishlist">
    <div class="block-title">
        <?php $_itemCount = $this->helper('wishlist')->getItemCount(); ?>
        <?php if ($_itemCount == 1): ?>
        <p>There is <a href="<?php echo $this->helper('wishlist')->getListUrl() ?>" title="<?php echo $this->__('Go to Wishlist') ?>">1 item</a> in your wishlist.</p>
        <?php else: ?>
        <p>There are <a href="<?php echo $this->helper('wishlist')->getListUrl() ?>" title="<?php echo $this->__('Go to Wishlist') ?>"><?php echo $_itemCount ?> items</a> in your wishlist.</p>
        <?php endif; ?>
    </div>
    <div class="block-content">
    <p class="block-subtitle"><?php echo $this->__('Last Added Items') ?></p>
    <?php if ($this->hasWishlistItems()): ?>
    <ol class="mini-products-list" id="wishlist-sidebar">
     <?php foreach ($this->getWishlistItems() as $_item): ?>
        <li class="item">
            <a href="<?php echo $this->getProductUrl($_item) ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50); ?>" width="50" height="50" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
            <div class="product-details">
                <a href="<?php echo $this->getItemRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the wishlist?') ?>');" class="btn-remove"><?php echo $this->__('Remove This Item') ?></a>
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
                <?php echo $this->getPriceHtml($_item, false, '-wishlist') ?>
                <?php if ($_item->isSaleable()): ?>
                    <a href="<?php echo $this->getAddToCartItemUrl($_item) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('wishlist-sidebar');</script>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your wishlist.') ?></p>
    <?php endif ?>
    </div>
</div>
<?php endif ?>
