<?php /* @var $this Mage_Page_Block_Html_Breadcrumbs */ ?>
<div id="wdn_navigation_bar">
    <div id="breadcrumbs">
        <!-- WDN: see glossary item 'breadcrumbs' -->
        <!-- TemplateBeginEditable name="breadcrumbs" -->
        <ul>
            <li><a href="http://www.unl.edu/" title="University of Nebraska&ndash;Lincoln">UNL</a></li>
            <?php if (Mage::app()->getStore()->getCode() == 'default'): ?>
            <li class="selected">
                <a href="<?php echo $this->getBaseUrl(); ?>">Marketplace</a>
            </li>
            <?php else: ?>
            <li>
                <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'default/'; ?>">Marketplace</a>
                <div class="storednav">
                    <?php echo $this->getChildHtml('store_switcher') ?>
                </div>
            </li>
            <li class="selected">
                <a href="<?php echo $this->getBaseUrl(); ?>"><?php echo $this->htmlEscape(Mage::app()->getGroup()->getName()) ?></a>
            </li>
            <?php endif;?>
            <?php if($crumbs && is_array($crumbs)): ?>
            <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
                <?php if ($_crumbName === 'home') { continue; } ?>
                <li class="<?php echo $_crumbName ?>">
                <?php if($_crumbInfo['link']): ?>
                    <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a>
                    <div class="storednav">
                        <?php echo $this->getChildHtml('topMenu') ?>
                    </div>
                <?php else: ?>
                    <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
                <?php endif; ?>
                </li>
            <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    <!-- TemplateEndEditable --></div>
    <div id="wdn_navigation_wrapper">
        <div id="navigation"><!-- TemplateBeginEditable name="navlinks" -->
        <?php if (Mage::app()->getStore()->getCode() == 'default'): ?>
            <?php echo $this->getChildHtml('store_switcher') ?>
        <?php else: ?>
            <?php echo $this->getChildHtml('topMenu') ?>
        <?php endif; ?>
        <!-- TemplateEndEditable --></div>
    </div>
</div>
