<?php if ($this->displayNotice()): ?>
<div class="no-display wdn_notice <?php echo $this->getNoticeType() ?>">
    <div class="close"><a title="Close this notice" href="#">Close this notice</a></div>
    <div class="message">
        <div class="title"><?php echo $this->escapeHtml($this->getNoticeTitle()) ?></div>
        <p><?php echo nl2br($this->escapeHtml($this->getNotice())) ?></p>
    </div>
</div>
<script type="text/javascript">
WDN.loadCSS(WDN.getTemplateFilePath('css/content/notice.css'));
WDN.loadJQuery(function() {
	if (!WDN.getCookie('mkpl_ack')) {
		WDN.jQuery('.wdn_notice').removeClass('no-display');
	}

	WDN.jQuery('.wdn_notice .close a').click(function() {
	    WDN.jQuery(this).closest('.wdn_notice').slideUp("slow", function() {
	        WDN.jQuery(this).remove();
	    });
	    var date = new Date();
	    var days = 7;
	    date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
	    document.cookie = "mkpl_ack=1;expires=" + date.toUTCString() + ";path=/";
	    return false;
	});
});
</script>
<?php endif; ?>
