<div id="footer">
    <div id="footer_floater"></div>
    <div class="footer_col">
        <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/feedback.html'); ?>
    </div>
    <div class="footer_col">
        <h3>Related Links</h3>
        <ul>
            <li><a href="http://www.huskers.com/">Athletics</a></li>
            <li><a href="http://www.liedcenter.org/">Lied Center for Performing Arts</a></li>
        </ul>
    </div>
    <div class="footer_col">
        <h3>Contacting Us</h3>
        <div class="contact">
            <?php echo $this->getChildHtml('contact_link') ?>
            <address><?php echo nl2br(Mage::getStoreConfig('contacts/contacts/address')) ?></address>
        </div></div>
    <div class="footer_col">
        <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/socialmediashare.html'); ?>
    </div>

    <div id="wdn_copyright">
        <div class="col-links left">
            <div class="link-col left">
                <div><strong>Store Exclusive</strong></div>
                <?php echo $this->getChildHtml('footer_links') ?>
            </div>
            <div class="link-col">
                <div><strong>UNL Marketplace</strong></div>
                <?php echo $this->getChildHtml('marketplace_links') ?>
            </div>
        </div>
        <div class="col-payment right">
            <a href="<?php echo $this->getUrl('', array('_direct' => 'about-us', '_fragment' => 'payment')) ?>"><img src="<?php echo $this->getSkinUrl('images/payment_methods.gif')?>" alt="Accepted Credit Cards: Visa, MasterCard, Discover" /></a>
        </div>
        <div class="clearer"></div>
        <p>Powered By Magento <?php echo $this->__('(ver. %s)', Mage::getVersion()) ?></p><br />
        <?php echo $this->getCopyright() ?>
        <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/wdn.html'); ?>
        | <a href="http://validator.unl.edu/check/referer">W3C</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer?profile=css3">CSS</a> <a href="http://www.unl.edu/" title="UNL Home" id="wdn_unl_wordmark"><img src="/wdn/templates_3.0/css/footer/images/wordmark.png" alt="UNL's wordmark" /></a>
    </div>
</div>
