<footer id="footer">
    <div id="footer_floater"></div>
    <div class="footer_col" id="wdn_footer_feedback">
        <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.1/includes/feedback.html'); ?>
    </div>
    <div class="footer_col" id="wdn_footer_related">
        <!-- InstanceBeginEditable name="leftcollinks" -->
        <h3>Related Links</h3>
        <ul>
            <li><a href="http://www.huskers.com/">Athletics</a></li>
            <li><a href="http://www.liedcenter.org/">Lied Center for Performing Arts</a></li>
        </ul>
        <!-- InstanceEndEditable -->
    </div>
    <div class="footer_col" id="wdn_footer_contact">
        <!-- InstanceBeginEditable name="contactinfo" -->
        <h3>Contacting Us</h3>
        <div class="contact">
            <?php echo $this->getChildHtml('contact_link') ?>
            <?php if (Mage::app()->getStore()->getCode() == 'default'): ?>
            <p style="margin:10px 0">
                <em>Please note:</em> The following customer support number is <b>NOT</b> for any specific store, rather, it is for all stores in the UNL Marketplace. To contact a specific store, please visit that store's page by using one of the links above.
            </p>
            <?php endif;?>
            <address><?php echo nl2br(Mage::getStoreConfig('general/store_information/address')) ?></address>
            <p><?php echo $this->__('Customer Support')?>: <?php echo Mage::getStoreConfig('general/store_information/phone') ?></p>
            <?php if (Mage::app()->getStore()->getCode() == 'default'): ?>
            <p style="margin:10px 0">
                Again, this number does <b>NOT</b> ring the Computer Shop.
            </p>
            <?php endif;?>
        </div>
        <!-- InstanceEndEditable -->
    </div>
    <div class="footer_col" id="wdn_footer_share">
        <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.1/includes/socialmediashare.html'); ?>
    </div>
    <!-- InstanceBeginEditable name="optionalfooter" -->
    <?php echo $this->getChildHtml('optional_footer') ?>
    <!-- InstanceEndEditable -->
    <div id="wdn_copyright">
        <div>
            <!-- InstanceBeginEditable name="footercontent" -->
            &copy; <?php echo date('Y') ?> <?php echo $this->getCopyright() ?>
            <br />
            <p>This site is powered by <a href="http://www.magentocommerce.com/">Magento</a><sup>&reg;</sup></p>
            <!-- InstanceEndEditable -->
            <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.1/includes/wdn.html'); ?>
        </div>
        <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.1/includes/logos.html'); ?>
    </div>
</footer>
