<div id="footer">
    <div id="footer_floater"></div>
    <div class="footer_col">
        <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/feedback.html'); ?>
    </div>
    <div class="footer_col"><!-- TemplateBeginEditable name="leftcollinks" -->
        <h3>Related Links</h3>
        <ul>
            <li><a href="http://www.huskers.com/">Athletics</a></li>
            <li><a href="http://www.liedcenter.org/">Lied Center for Performing Arts</a></li>
        </ul>
    <!-- TemplateEndEditable --></div>
    <div class="footer_col"><!-- TemplateBeginEditable name="contactinfo" -->
        <h3>Contacting Us</h3>
        <div class="contact">
            <?php echo $this->getChildHtml('contact_link') ?>
            <?php if (Mage::app()->getStore()->getCode() == 'default'): ?>
            <p style="margin:10px 0">
                <em>Please note:</em> The following customer support number is <b>NOT</b> for any specific store, rather, it is for all stores in the UNL Marketplace. To contact a specific store, please visit that store's page by using one of the links above.
            </p>
            <?php endif;?>
            <address><?php echo nl2br(Mage::getStoreConfig('general/store_information/address')) ?></address>
            <p><?php echo $this->__('Customer Support')?>: <?php echo Mage::getStoreConfig('general/store_information/phone') ?></p>
            <?php if (Mage::app()->getStore()->getCode() == 'default'): ?>
            <p style="margin:10px 0">
                Again, this number does <b>NOT</b> ring the Computer Shop.
            </p>
            <?php endif;?>
        </div><!-- TemplateEndEditable --></div>
    <div class="footer_col">
        <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/socialmediashare.html'); ?>
    </div>
    <!-- TemplateBeginEditable name="optionalfooter" -->
    <div class="footer_sep"></div>
    <div class="opfooter three_col left">
        <div class="link-col left">
            <div><strong>Store Exclusive</strong></div>
            <?php echo $this->getChildHtml('footer_links') ?>
        </div>
        <div class="link-col">
            <div><strong>UNL Marketplace</strong></div>
            <?php echo $this->getChildHtml('marketplace_links') ?>
        </div>
    </div>
    <div class="opfooter col right footer-payment">
        <a href="<?php echo $this->getUrl('', array('_direct' => 'about-us', '_fragment' => 'payment')) ?>"><img src="<?php echo $this->getSkinUrl('images/payment_methods.gif')?>" alt="Accepted Credit Cards: Visa, MasterCard, Discover" /></a>
    </div>
    <div class="clear"></div>
    <!-- TemplateEndEditable -->
    <div id="wdn_copyright"><!-- TemplateBeginEditable name="footercontent" -->
        <p>Powered By Magento</p><br />
        <?php echo $this->getCopyright() ?>
        <!-- TemplateEndEditable -->
        <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/wdn.html'); ?>
        | <a href="http://validator.unl.edu/check/referer">W3C</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer?profile=css3">CSS</a> <a href="http://www.unl.edu/" title="UNL Home" id="wdn_unl_wordmark"><img src="/wdn/templates_3.0/css/footer/images/wordmark.png" alt="UNL's wordmark" /></a>
    </div>
</div>
