<?php /* @var $this Mage_Page_Block_Html_Head */ ?>
<!--
    Membership and regular participation in the UNL Web Developer Network
    is required to use the UNL templates. Visit the WDN site at
    http://wdn.unl.edu/. Click the WDN Registry link to log in and
    register your unl.edu site.
    All UNL template code is the property of the UNL Web Developer Network.
    The code seen in a source code view is not, and may not be used as, a
    template. You may not use this code, a reverse-engineered version of
    this code, or its associated visual presentation in whole or in part to
    create a derivative work.
    This message may not be removed from any pages based on the UNL site template.

    $Id: php.fixed.dwt.php 536 2009-07-23 15:47:30Z bbieber2 $
-->
<title>
<?php if (substr($this->getTitle(), 0, 3) == 'UNL'): ?>
    <?php echo $this->getTitle() ?>
<?php else: ?>
    UNL | Marketplace<?php if (Mage::app()->getStore()->getCode() != 'default'): ?> | <?php echo $this->htmlEscape(Mage::app()->getGroup()->getName()) ?><?php endif; ?> | <?php echo $this->getTitle() ?>
<?php endif; ?>
</title>
<link rel="home" href="<?php echo $this->getBaseUrl() ?>" />
<?php if (Mage::helper('unl_cas')->getAuth()->isLoggedIn()): ?>
<link rel="logout" href="<?php echo $this->getUrl('customer/account/logout') ?>" />
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>

<link rel="stylesheet" type="text/css" media="screen" href="/wdn/templates_3.0/css/all.css" />
<link rel="stylesheet" type="text/css" media="print" href="/wdn/templates_3.0/css/print.css" />
<script type="text/javascript" src="/wdn/templates_3.0/scripts/all.js"></script>
<?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/browserspecifics.html'); ?>
<?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/metanfavico.html'); ?>

<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
