<?php /* @var $this Mage_Page_Block_Template_Links */ ?>
<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
        <ul class="toplinks"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
            <?php foreach($_links as $_link): ?>
            <?php $_class = ''; ?>
            <?php if ($_link->getIsFirst()) { $_class .= 'first '; } ?>
            <?php if ($_link->getIsLast()) { $_class .= 'last '; } ?>
            <li<?php if (!empty($_class)): ?> class="<?php echo $_class ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" <?php echo $_link->getAParams() ?>><span><?php echo $_link->getLabel() ?></span></a><?php echo $_link->getAfterText() ?>
            <?php if ($_link->getLabel() == 'Your Cart'): ?>
                <?php echo $this->getChildHtml('cart_sidebar') ?>
            <?php elseif ($_link->getLabel() == 'Your Wishlist'): ?>
                <?php echo $this->getChildHtml('wishlist') ?>
            <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
<?php endif; ?>
