<?php /* @var $this Mage_Sales_Block_Order_Email_Shipment_Items */ ?>
<?php /* @var $_order Unl_Core_Model_Sales_Order */ ?>
<?php $_shipment = $this->getShipment() ?>
<?php $_order    = $this->getOrder() ?>
<?php if ($_shipment && $_order): ?>
<table cellspacing="0" cellpadding="0" border="0" width="100%">
    <?php foreach ($_shipment->getAllItems() as $_item): ?>
    <?php if($_item->getOrderItem()->getParentItem()) continue; ?>
    <tbody>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>
</table>
<?php endif; ?>
