<?php /* @var $this Mage_Page_Block_Html */?>
<!DOCTYPE html>
<!--[if IEMobile 7 ]><html class="ie iem7"><![endif]-->
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"><![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"><![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"><![endif]-->
<!--[if (gte IE 9)|(gt IEMobile 7) ]><html class="ie" lang="en"><![endif]-->
<!--[if !(IEMobile) | !(IE)]><!--><html lang="en"><!-- InstanceBegin template="/Templates/php.local.dwt.php" codeOutsideHTMLIsLocked="false" --><!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-print<?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
<div class="wdn-band">
    <div class="wdn-grid-set print-head">
        <div class="wdn-col-one-third">
            <img src="<?php echo $this->getPrintLogoUrl() ? $this->getPrintLogoUrl() : $this->getSkinUrl('images/logo_print.gif') ?>" class="logo" alt="" />
        </div>
        <?php if ($this->getPrintLogoText()):?>
        <div class="wdn-col-two-thirds">
            <address><?php echo nl2br($this->htmlEscape($this->getPrintLogoText())) ?></address>
        </div>
        <?php endif;?>
    </div>
    <?php echo $this->getChildHtml('content') ?>
    <div class="buttons-set">
        <button type="button" title="<?php echo $this->__('Close Window') ?>" class="button" onclick="window.close();"><span><span><?php echo $this->__('Close Window') ?></span></span></button>
    </div>
    <?php echo $this->getAbsoluteFooter() ?>
</div>
</body>
</html>
