<!-- menu start -->

<!-- menu end -->
<div class="nav-bar">
<?php drawMenuLevel($this->getMenuArray()); ?>
<?php function drawMenuLevel($_menu, $_level=0) { ?>
    <ul <?php if(!$_level): ?>id="nav"<?php endif ?>>
        <?php foreach ($_menu as $_item): ?>
        <li <?php if(!empty($_item['children'])): ?>onmouseover="Element.addClassName(this,'over')" onmouseout="Element.removeClassName(this,'over')"<?php endif ?> class=" <?php echo (!$_level && !empty($_item['active']))?' active':'' ?> <?php echo !empty($_item['children'])?' parent':'' ?><?php echo (!empty($_level) && !empty($_item['last']))?' last':'' ?> level<?php echo $_level ?>"> <a href="<?php echo $_item['url'] ?>" <?php if(!empty($_item['title'])): ?>title="<?php echo $_item['title'] ?>"<?php endif ?> <?php if(!empty($_item['click'])): ?>onclick="<?php echo $_item['click']; ?>"<?php endif ?> class="<?php echo ($_level===0 && !empty($_item['active']))?'active':'' ?>"><span><?php echo Mage::helper('adminhtml')->escapeHtml($_item['label']) ?><?php if(!$_level): ?><?php endif ?></span></a>
            <?php if(!empty($_item['children'])): ?>
                <?php drawMenuLevel($_item['children'], $_level+1); ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
    </ul>
<?php }//function ?>

    <a id="page-help-link" href="<?php echo Mage::helper('adminhtml')->getPageHelpUrl() ?>"><?php echo $this->__('Get help for this page') ?></a>
    <script type="text/javascript">$('page-help-link').target = 'magento_page_help'</script>

</div>

