<?php /* @var $this Mage_Checkout_Block_Multishipping_Billing */ ?>
<div class="multiple-checkout">
    <div class="page-title">
        <h1><?php echo $this->__('Billing Information') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <script src="<?php echo Mage::getBaseUrl('js') ?>varien/payment.js" type="text/javascript"></script>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="multishipping-billing-form">
        <div class="wdn-grid-set">
            <div class="bp2-wdn-col-one-third">
                <div class="box">
                    <div class="box-title">
                        <h2><?php echo $this->__('Billing Address') ?> <a href="<?php echo $this->getSelectAddressUrl() ?>" title="<?php echo $this->__('Change') ?>"><i class="mrkp-icon-edit"></i></a></h2>
                    </div>
                    <div class="box-content">
                        <?php $_address=$this->getAddress() ?>
                        <address><?php echo $_address->format('html') ?></address>
                    </div>
                </div>
            </div>
            <div class="bp2-wdn-col-two-thirds">
                <div class="box">
                    <div class="box-title">
                        <h2><?php echo $this->__('Payment Method') ?></h2>
                    </div>
                    <div class="box-content">
                        <!-- Payment methods forms list -->
                        <?php
                            $_methods = $this->getMethods();
                            $oneMethod = count($_methods) <= 1;
                        ?>
                        <div class="sp-methods">
                        <ul class="form-list wdn-grid-set-halves wdn-grid-clear">
                        <?php foreach ($_methods as $_method): ?>
                            <?php $_code = $_method->getCode(); ?>
                            <li class="wdn-col control">
                                <?php if(!$oneMethod): ?>
                                <input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio mrkp-radio-btn" />
                                <?php else :?>
                                <span class="no-display"><input type="radio" id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" name="payment[method]" checked="checked" class="radio" /></span>
                                <?php endif;?>
                                <label for="p_method_<?php echo $_code ?>" class="mrkp-btn-cnt"><i class="mrkp-icon-"></i><span class="mrkp-btn-noun"><?php echo $_method->getTitle() ?></span></label>
                            </li>
                        <?php endforeach; ?>
                        </ul></div>
                        <div class="sp-methods">
                        <ul>
                        <?php foreach ($_methods as $_method): ?>
                            <?php $_code = $_method->getCode(); ?>
                            <li class="wdn-col control">
                                <?php if($html = $this->getChildHtml('payment.method.'.$_code)) : ?>
                                <?php echo $html; ?>
                                <?php endif;?>
                            </li>
                        <?php endforeach; ?>
                        </ul></div>
                        <div id="cvv_visual" class="no-js-show">
                            <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
                        </div>
                        <?php echo $this->getChildHtml('checkout_billing_items') ?>
                    </div>
                </div>
            </div>
        </div>
        <p>You will have a chance to review your order in the next step, before you place your order.</p>
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Shipping Information') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Continue to Review Your Order') ?>" class="button"><span><span><?php echo $this->__('Continue to Review Your Order') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var payment = new paymentForm('multishipping-billing-form');
        require(['jquery'], function($) {
            window.toggleToolTip = function(event) {
            	event.preventDefault();
            	$('#cvv_visual').toggle();
            };

            $('.cvv-what-is-this').click(toggleToolTip);
        });
    //]]>
    </script>
</div>
