<?php
/**
 * Mustishipping state
 *
 * @see Mage_Checkout_Block_Multishipping_State
 */
/* @var $this Mage_Checkout_Block_Multishipping_State */
?>
<ul class="checkout-progress clearer" id="checkout-progress-state">
<?php foreach ($this->getSteps() as $_step): ?>
    <li title="<?php echo $_step->getLabel() ?>"<?php if($_step->getIsActive()): ?> class="active"<?php endif; ?>><span><?php echo $_step->getLabel() ?></span></li>
<?php endforeach; ?>
</ul>
<script type="text/javascript">decorateGeneric($$('#checkout-progress-state li'), ['first','last']);</script>
