<?php $_wishlistItem = $this->getWishlistItem(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getUpdateUrl($_wishlistItem); ?>
<ul class="add-to-links">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist wdn-button"><?php echo $this->__('Update Wishlist') ?></a></li>
<?php endif; ?>
<?php $_product = $this->getProduct(); ?>
<?php $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product); ?>
<?php if ($_compareUrl) : ?>
    <li><a href="<?php echo $_compareUrl ?>" class="link-compare wdn-button"><?php echo $this->__('Add to Compare') ?></a></li>
<?php endif; ?>
</ul>
