<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<!--[if IEMobile 7 ]><html class="ie iem7"><![endif]-->
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"><![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"><![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"><![endif]-->
<!--[if (gte IE 9)|(gt IEMobile 7) ]><html class="ie" lang="en"><![endif]-->
<!--[if !(IEMobile) | !(IE)]><!--><html lang="en"><!-- InstanceBegin template="/Templates/php.local.dwt.php" codeOutsideHTMLIsLocked="false" --><!--<![endif]-->
<head>
<?php echo $this->getChildHtml('head') ?>
<!-- InstanceParam name="class" type="text" value="popup" -->
</head>
<body class="popup<?php echo $this->getBodyClass() ? ' ' . $this->getBodyClass() : '' ?>" data-version="3.1">
    <?php echo $this->getChildHtml('after_body_start') ?>
    <nav class="skipnav">
        <a class="skipnav" href="#maincontent">Skip Navigation</a>
    </nav>
    <div id="wdn_wrapper">
        <?php echo $this->getChildHtml('header') ?>
        <?php echo $this->getChildHtml('breadcrumbs') ?>
        <div id="wdn_content_wrapper">
            <div id="pagetitle">
                <!-- InstanceBeginEditable name="pagetitle" -->
                <!-- InstanceEndEditable -->
            </div>
            <div id="maincontent" role="main">
                <!--THIS IS THE MAIN CONTENT AREA; WDN: see glossary item 'main content area' -->
                <!-- InstanceBeginEditable name="maincontentarea" -->
                <?php echo $this->getChildHtml('content') ?>
                <!-- InstanceEndEditable -->
                <div class="clear"></div>
                <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.1/includes/noscript.html'); ?>
                <!--THIS IS THE END OF THE MAIN CONTENT AREA.-->
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
    <?php echo $this->getAbsoluteFooter() ?>
</body>
<!-- InstanceEnd --></html>
