<script type="text/javascript">
//<![CDATA[
if(!window.toggleVisibilityOnObjects) {
    var toggleVisibilityOnObjects = function(source, objects) {
        if($(source) && $(source).checked) {
            objects.each(function(item){
                $(item).show();
                $$('#' + item + ' .input-text').each(function(item) {
                    item.removeClassName('validation-passed');
                });
            });


        } else {
            objects.each(function(item){
                $(item).hide();
                $$('#' + item + ' .input-text').each(function(sitem) {
                    sitem.addClassName('validation-passed');
                });
            });

        }

    }
}
//]]>
</script>
<div class="delivery-date">
    <p class="control">
        <input type="checkbox" id="toggle-delivery-date" name="toggle-delivery-date" value="1" onclick="toggleVisibilityOnObjects(this, ['delivery-date-container']);"<?php if(Mage::getSingleton('customer/session')->getDeliveryNotice() || Mage::getSingleton('customer/session')->getDeliveryDate()): ?> checked="checked"<?php endif; ?> class="checkbox" />
        <label for="toggle-delivery-date"><?php echo $this->__('Would you like to delay shipping or specify a pickup date?') ?></label>
    </p>
</div>
<div id="delivery-date-container" class="delivery-date-form">
    <dl class="fields">
    	<dt>
    		<label for="<?php echo $this->getInputId() ?>"><?php echo $this->__("Delivery Date");?></label>
    	</dt>
    	<dd class="input-box"><div><?php echo $this->getCalendarHtml()?></div>
    	<?php if(Mage::getStoreConfig(AW_Deliverydate_Helper_Config::XML_PATH_GENERAL_TIME_NOTICE_ENABLED)): ?>
    		<em><?php echo $this->__("Please note that orders after %s will be delivered the next day", $this->getFormattedTime())?></em>
    	<?php endif; ?>
    	</dd>

    	<?php if(Mage::getStoreConfig(AW_Deliverydate_Helper_Config::XML_PATH_GENERAL_NOTICE_ENABLED)): ?>
    	<dt>
    		<label for="aw_deliverydate_notice"><?php echo $this->__("Delivery Notice");?></label>
    	</dt>
    	<dd class="input-box"><textarea id="aw_deliverydate_notice" name="aw_deliverydate_notice" cols="64" rows="5" class="input-text"><?php echo Mage::getSingleton('customer/session')->getDeliveryNotice()?></textarea></dd>
    	<?php endif; ?>
    </dl>
</div>
<script type="text/javascript">
//<![CDATA[
    toggleVisibilityOnObjects('toggle-delivery-date', ['delivery-date-container']);
//]]>
</script>