<?php /* @var $this Unl_Core_Block_Email_Order_Instructions */ ?>
<?php if ($this->canShow()): ?>
<table border="0" cellpadding="0" cellspacing="0" width="100%" style="line-height: normal;">
  <tr>
       <td bgcolor="#137CBD" style="padding: 50px 15px 50px 15px;" class="section-padding">
             <table align="center" border="0" cellpadding="0" cellspacing="0" width="620" class="responsive-table">
                  <tr>
                       <td valign="middle">
                            <table border="0" cellspacing="0" cellpadding="0" width="100%">
                            	<tr>
									 <td align="left" valign="top">
										  <table width="100%" border="0" cellspacing="0" cellpadding="0">
										      <tr>
													<td align="left" style="font-size: 25px; font-family: Helvetica, Arial, sans-serif; color: #ffffff;">
													    Additional Information
													</td>
											   </tr>
											   <?php $last = count($this->getProducts()) - 1; ?>
											   <?php $i = 0; ?>
											   <?php foreach ($this->getProducts() as $product): ?>
											   <tr>
													<td style="font-size: 13px; line-height: 17px; font-family: Georgia, serif; color: #ffffff; padding-top:20px;">
													    Regarding your <?php echo $this->escapeHtml($product->getName()) ?>:
													</td>
											   </tr>
											   <tr>
													<td style="font-size: 17px; line-height: 27px; font-family: Georgia, serif; color: #ffffff;<?php if ($i < $last): ?> padding-bottom:10px; border-bottom: 1px solid #0E5782;<?php endif;?>">
													    <?php echo $this->getProductInstructions($product) ?>
													</td>
											   </tr>
											       <?php $i++; ?>
											   <?php endforeach; ?>
										  </table>
									 </td>
                           		 </tr>
                            </table>
                       </td>
                  </tr>
             </table>
       </td>
  </tr>
</table>
<?php endif; ?>
