<?php $_order = $this->getOrder() ?>
<?php
$thColor = Mage::getModel('core/variable')
    ->setStoreId($_order->getStoreId())
    ->loadByCode('email_th_color')
    ->getValue('html');
$thBg = Mage::getModel('core/variable')
    ->setStoreId($_order->getStoreId())
    ->loadByCode('email_th_bg')
    ->getValue('html');
?>
<?php if ($_order): ?>
<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th align="left" bgcolor="<?php echo $thBg ?>" style="padding:3px 9px;border-bottom:2px solid #BEBCB7;color:<?php echo $thColor ?>;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Item') ?></th>
            <th align="left" bgcolor="<?php echo $thBg ?>" style="padding:3px 9px;border-bottom:2px solid #BEBCB7;color:<?php echo $thColor ?>;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Sku') ?></th>
            <th align="center" bgcolor="<?php echo $thBg ?>" style="padding:3px 9px;border-bottom:2px solid #BEBCB7;color:<?php echo $thColor ?>;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Qty') ?></th>
            <th align="right" bgcolor="<?php echo $thBg ?>" style="padding:3px 9px;border-bottom:2px solid #BEBCB7;color:<?php echo $thColor ?>;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>

    <?php $i=0; foreach ($_order->getAllItems() as $_item): ?>
    <?php if($_item->getParentItem()) continue; else $i++; ?>
    <tbody<?php echo $i%2 ? ' bgcolor="#eeeded"' : '' ?>>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>

    <tbody>
        <?php echo $this->getChildHtml('order_totals') ?>
    </tbody>
</table>
<?php if ($this->helper('giftmessage/message')->isMessagesAvailable('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
    <?php $_giftMessage = $this->helper('giftmessage/message')->getGiftMessage($_order->getGiftMessageId()); ?>
    <?php if ($_giftMessage): ?>
<br />
<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th align="left" bgcolor="#d9e5ee" style="font-size:13px; padding:3px 9px"><strong><?php echo $this->__('Gift Message for this Order') ?></strong></th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td colspan="4" align="left" style="padding:3px 9px">
            <strong><?php echo $this->__('From:'); ?></strong> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?>
            <br /><strong><?php echo $this->__('To:'); ?></strong> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?>
            <br /><strong><?php echo $this->__('Message:'); ?></strong><br /> <?php echo $this->htmlEscape($_giftMessage->getMessage()) ?>
            </td>
        </tr>
    </tbody>
</table>
    <?php endif; ?>
<?php endif; ?>
<?php endif; ?>
