<?php $_order = $this->getOrder() ?>
<?php if (Mage::helper('unl_core/shipping_pickup')->isMethodPickup($_order->getShippingMethod())): ?>
    <?php $_pickupStore = current($_order->getAllVisibleItems())->getSourceStoreView(); ?>
    <p><strong><?php echo $this->__('Pickup Location:')?></strong><br />
    <?php echo nl2br(Mage::helper('unl_core/shipping_pickup')->getPickupLocation($_order->getShippingMethod(), $_pickupStore)) ?></p>
<?php endif; ?>
