<?php /* @var $this Mage_Core_Block_Template */ ?>
</h2>
                        </td>
                    </tr>
                    <tr height="25">
                        <td colspan="2" style="line-height:0;" height="25">
                            <img src="http://www.unl.edu/wdn/templates_3.0/images/email/email2_06.gif" width="556" height="25" alt="" />
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="EEEEEE" width="12">
                            &nbsp;
                        </td>
                        <td bgcolor="FFFFFF" width="10">
                            &nbsp;
                        </td>
                        <td width="556" colspan="2" valign="top">
