<?php /* @var $this Mage_Core_Block_Template */ ?>
                        </td>
                        <td bgcolor="FFFFFF" width="10">
                            &nbsp;
                        </td>
                        <td bgcolor="EEEEEE" width="12">
                            &nbsp;
                        </td>
                    </tr>
                    <tr bgcolor="EEEEEE">
                        <td colspan="6" valign="top" style="line-height:0;" width="600">
                            <img src="http://www.unl.edu/wdn/templates_3.0/images/email/email3_10.gif" width="600" height="51" alt="" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6" valign="top" width="600">
                            <table bgcolor="EEEEEE" style="background:#eeeeee;" width="600" border="0" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td width="22">
                                        &nbsp;
                                    </td>
                                    <td width="556" style="color:#606060;font-size:10px;line-height:1em;min-height:42px;">
                                        <p style="line-height:1.1em;">
                                            <img src="http://www.unl.edu/wdn/templates_3.0/images/email/wordmark.png" alt="" width="90" height="37" align="right" />
                                            &copy; <?php echo date('Y') ?> University of Nebraska&ndash;Lincoln<br />
                                            UNL Marketplace | 420 Nebraska Hall , Lincoln, NE 68588-0525 |  402-472-9964
                                        </p>
                                    </td>
                                    <td width="22">
                                        &nbsp;
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="6" style="line-height:0;" width="600">
                            <img src="http://www.unl.edu/wdn/templates_3.0/images/email/email3_14.gif" width="600" height="12" alt="" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
</body>
