<?php /* @var $this Mage_Core_Block_Template */ ?>
<body style="margin:0; padding:0; color:#494949; font-family: 'Lucida Grande',Verdana,Arial; font-size:12px; line-height:1.4;">
<div style="color:#494949; font-family:'Lucida Grande',Verdana,Arial; font-size:12px; line-height:1.4;">
    <table cellspacing="0" cellpadding="0" border="0" width="98%" style="margin-top:10px; margin-bottom:10px;">
        <tr>
            <td align="center" valign="top">
                <table width="600" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                        <td rowspan="3" colspan="2" style="line-height:0;" width="22" background="http://www.unl.edu/wdn/templates_3.0/images/email/email2_07.gif" bgcolor="EEEEEE" valign="top">
                            <img src="http://www.unl.edu/wdn/templates_3.0/images/email/email2_01.gif" width="22" height="95" alt="" />
                        </td>
                        <td rowspan="2" valign="top" style="line-height:0;">
                            <a href="<?php echo $this->getUrl('') ?>" style="outline:none;display:block">
                                <img src="http://www.unl.edu/wdn/templates_3.0/images/email/email2_02.gif" width="67" height="70" alt="" />
                            </a>
                        </td>
                        <td valign="top" style="line-height:0;">
                            <img src="http://www.unl.edu/wdn/templates_3.0/images/email/email2_03.gif" width="489" height="31" alt="" />
                        </td>
                        <td rowspan="3" colspan="2" style="line-height:0;" width="22" background="http://www.unl.edu/wdn/templates_3.0/images/email/email2_09.gif" bgcolor="EEEEEE" valign="top">
                            <img src="http://www.unl.edu/wdn/templates_3.0/images/email/email2_04.gif" width="22" height="95" alt="" />
                        </td>
                    </tr>
                    <tr>
                        <td valign="top">
                            <h1 style="color:#565656;font-family:arial;text-decoration:none;font-size:30px;line-height:1;font-weight:bold;margin:0;margin-top:3px;">UNL MARKETPLACE</h1>
                            <h2 style="color:#565656;font-family:arial;text-decoration:none;font-size:10px;line-height:1;font-weight:normal;margin:0;padding-top:0px;padding-bottom:0;">
