<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body class="html5 mobile<?php echo $this->getBodyClass()?' '.$this->getBodyClass():'' ?>">
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<p class="skipnav"> <a class="skipnav" href="#maincontent">Skip Navigation</a> </p>
<div id="wdn_wrapper">
    <?php echo $this->getChildHtml('header') ?>
    <?php echo $this->getChildHtml('breadcrumbs') ?>
    <div id="wdn_content_wrapper">
        <div id="titlegraphic"><!-- TemplateBeginEditable name="titlegraphic" -->
        <?php if (Mage::app()->getStore()->getCode() == 'default'): ?>
            <h1>Marketplace</h1>
        <?php else: ?>
            <h1><?php echo $this->htmlEscape(Mage::app()->getGroup()->getName()); ?></h1>
        <?php endif; ?>
        <!-- TemplateEndEditable --></div>
        <div id="pagetitle"><!-- TemplateBeginEditable name="pagetitle" --> <!-- TemplateEndEditable --></div>
        <div id="maincontent">
            <!--THIS IS THE MAIN CONTENT AREA; WDN: see glossary item 'main content area' -->
            <!-- TemplateBeginEditable name="maincontentarea" -->
            <div id="top_messages">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content_notices') ?>
            </div>
            <?php echo $this->getChildHtml('content') ?>
            <div id="common_footer">
                <?php echo $this->getChildHtml('footer') ?>
            </div>
            <div id="mobile_help">
                <a href="?mobile=no" id="mobileNo">Non-mobile version</a>
                <?php echo $this->getChildHtml('contact_link') ?>
            </div>
            <!-- TemplateEndEditable -->
            <div class="clear"></div>
            <?php echo Mage::helper('unl_core')->fetchServerFile('/wdn/templates_3.0/includes/noscript.html'); ?>
            <!--THIS IS THE END OF THE MAIN CONTENT AREA.-->
        </div>
    </div>
    <div id="wdn_wrapper_footer"> </div>
    <?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
