<?php /* @var $this Mage_Core_Block_Template */ ?>
<?php /* @var $order Mage_Sales_Model_Order */?>
<?php $order = $this->getOrder(); ?>
<?php if (in_array($order->getState(), array(
    Mage_Sales_Model_Order::STATE_COMPLETE,
    Mage_Sales_Model_Order::STATE_CLOSED,
))): ?>
, and that this completes your order.
<?php else: ?>
, and we are still processing or awaiting payment for your order.
<?php endif; ?>
