<?php $_shipment=$this->getShipment() ?>
<?php $_order=$this->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<?php
$linkColor = Mage::getModel('core/variable')
    ->setStoreId($_order->getStoreId())
    ->loadByCode('email_link_color')
    ->getValue('html');
?>
<p style="margin:1.1em 0;"><a style="color:<?php echo $linkColor ?>;" href="<?php echo Mage::helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>">Track order</a></p>
<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #EAEAEA;">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Shipped By') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php $i=0; foreach ($_shipment->getAllTracks() as $_item): $i++ ?>
        <tr <?php echo $i%2?'bgcolor="#F6F6F6"':'' ?>>
            <td align="left" valign="top" style="padding:3px 9px"><?php echo $_item->getTitle() ?></td>
            <td align="center" valign="top" style="padding:3px 9px"><?php echo $_item->getNumber() ?></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif; ?>
