<!-- TemplateBeginEditable name="sitebranding_logo" -->
<a id="logo" href="<?php echo $this->getLogoLink() ?>" title="<?php echo $this->getLogoLabel() ?>"><?php echo $this->getLogoLabel() ?></a>
<!-- TemplateEndEditable -->
<span id="wdn_institution_title"><!-- TemplateBeginEditable name="sitebranding_affiliate" --><a href="http://www.unl.edu" title="University of Nebraska&ndash;Lincoln">An affiliate of the University of Nebraska&ndash;Lincoln</a><!-- TemplateEndEditable --></span>
