<?php /* @var $this Unl_BundlePlus_Block_Sales_Order_Items_Renderer */ ?>
<?php /* @var $_item Mage_Sales_Model_Order_Invoice_Item */ ?>
<?php /* @var $_order Unl_Core_Model_Sales_Order */ ?>
<?php $_item = $parentItem = $this->getItem() ?>
<?php $items = $this->getChilds($parentItem) ?>
<?php $_order = $this->getItem()->getOrder(); ?>
<tr>
    <td align="left" valign="top" style="font-size: 17px; line-height: 27px; font-family: Georgia, serif; color: #545350; padding: 10px;">
        <?php if ($this->canShowPriceInfo($_item) && $_item->getQty() != 1): ?>
        <?php echo $_item->getQty() * 1 ?> of
        <?php endif; ?>
        <strong style="color:#137CBD"><?php echo $this->escapeHtml($_item->getName()) ?></strong><br />
        <em>SKU:</em> <?php echo $this->escapeHtml($_item->getSku()) ?>
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
            <dd style="margin:0; padding:0 0 0 9px;"><?php echo $option['value'] ?></dd>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php if ($this->canShowPriceInfo($_item) && count($items) > 1): ?>
        <?php $_prevOptionId = '' ?>
        <dl style="margin:10px 0; padding:0;">
            <?php foreach ($items as $_item): ?>
            <?php if (!$_item->getOrderItem()->getParentItem()) continue; ?>
            <?php $attributes = $this->getSelectionAttributes($_item) ?>
            <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <dt><strong><em><?php echo $attributes['option_label'] ?></em></strong></dt>
            <?php $_prevOptionId = $attributes['option_id'] ?>
            <?php endif; ?>
            <dd style="margin:0; padding:0 0 0 9px;">
                <?php echo $this->getValueHtml($_item)?><br />
                <em>SKU:</em> <?php echo $this->escapeHtml($_item->getSku()) ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php $_item = $parentItem; ?>
        <?php endif; ?>
        <?php echo $this->escapeHtml($_item->getDescription()) ?>
    </td>
    <td align="right" valign="top" style="font-size: 17px; line-height: 27px; font-family: Georgia, serif; color: #545350; padding: 10px;">
        <?php if ($this->canShowPriceInfo($_item)): ?>
        <?php if ($this->helper('tax')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
            <?php else: ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()) ?>
            <?php endif; ?>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <br />
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>


        <?php if ($this->helper('tax')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <br /><span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                    <?php echo $_order->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                <?php else: ?>
                    <?php echo $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $_order->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
        <?php endif; ?>
    </td>
</tr>
<?php if (!$this->canShowPriceInfo($_item)): ?>
<?php $_prevOptionId = '' ?>
<?php foreach ($items as $_item): ?>
<?php if (!$_item->getOrderItem()->getParentItem()) continue; ?>
<?php $attributes = $this->getSelectionAttributes($_item) ?>
<?php if ($_prevOptionId != $attributes['option_id']): ?>
<tr>
    <td align="left" valign="top" style="font-size: 17px; line-height: 27px; font-family: Georgia, serif; color: #545350; padding: 0 10px;"><strong><em><?php echo $attributes['option_label'] ?></em></strong></td>
    <td>&nbsp;</td>
</tr>
<?php $_prevOptionId = $attributes['option_id'] ?>
<?php endif; ?>
<tr>
    <td align="left" valign="top" style="font-size: 17px; line-height: 27px; font-family: Georgia, serif; color: #545350; padding: 0 10px 0 19px;">
        <?php if ($_item->getQty() != 1): ?>
        <?php echo $_item->getQty() * 1 ?> of
        <?php endif; ?>
        <?php echo $this->getValueHtml($_item)?><br />
        <em>SKU:</em> <?php echo $this->escapeHtml($_item->getSku()) ?>
    </td>
    <td align="right" valign="top" style="font-size: 17px; line-height: 27px; font-family: Georgia, serif; color: #545350; padding: 0 10px;">
        <?php if ($this->helper('tax')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
            <?php else: ?>
                <?php echo $_order->formatPrice($_item->getRowTotal()) ?>
            <?php endif; ?>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <br />
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>


        <?php if ($this->helper('tax')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                <br /><span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'email', $_order->getStore())): ?>
                    <?php echo $_order->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
                <?php else: ?>
                    <?php echo $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                <?php endif; ?>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                <br />
                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
                    <?php endforeach; ?>
                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                    <small>
                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo $_order->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
                    <?php endforeach; ?>
                    </small>
                <?php endif; ?>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $_order->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    </td>
</tr>
<?php endforeach; ?>
<?php endif; ?>
