<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="box base-mini mini-search">
    <div class="head">
        <h4 class="title">Search</h4>
    </div>
    <div class="content">
        <form id="localSearchForm" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
            <fieldset>
                <label class="overlabel" for="localSearchQuery-field"><?php echo $this->helper('catalogSearch')->__('Search entire store here...') ?></label>
                <input id="localSearchQuery-field" type="text" class="input-text" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogSearch')->getEscapedQueryText() ?>"/>
                <input name="localSearch-Button" id="localSearch-Button" src="/ucomm/templatedependents/templatecss/images/transpixel.gif" alt="Search" type="image" />
                <div id="search_autocomplete" class="search-autocomplete"></div>
                <script type="text/javascript">
                    var searchForm = new Varien.searchForm('localSearchForm', 'localSearchQuery-field', '');
                    searchForm.initAutocomplete('<?php echo $this->helper('catalogSearch')->getSuggestUrl() ?>', 'search_autocomplete');
                </script>
            </fieldset>
        </form>
    </div>
</div>