<?php
/* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */
?>
<?php if($this->helper('catalog/product_compare')->getItemCount()>0): ?>
<div class="zenbox soothing block block-compare">
    <h3>
        <?php echo $this->__('Compare Products') ?>
        <small><?php echo $this->__('(%d)', $this->helper('catalog/product_compare')->getItemCount()) ?></small>
    </h3>
    <ol id="compare-items">
    <?php foreach($this->helper('catalog/product_compare')->getItemCollection() as $_index=>$_item): ?>
        <li class="item">
            <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
            <a href="<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the comparison list?') ?>');"><?php echo $this->__('Remove This Item') ?></a>
            <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('compare-items')</script>
    <div class="actions">
        <a href="<?php echo $this->helper('catalog/product_compare')->getClearListUrl() ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');"><?php echo $this->__('Clear All') ?></a>
        <button type="button" title="<?php echo $this->__('Compare') ?>" class="button" onclick="popWin('<?php echo $this->helper('catalog/product_compare')->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo $this->__('Compare') ?></span></span></button>
    </div>
</div>
<?php endif; ?>
