<?php $scope = Mage::helper('unl_core')->getAdminUserScope(); ?>
<?php if ($this->isShow()): ?>
<p class="switcher"><label for="store_switcher"><?php echo $this->__('Show Report For') ?>:</label>
<select name="store_switcher" id="store_switcher" onchange="return switchStore(this);">
    <option value=""><?php echo $this->__('All') ?></option>
    <?php foreach ($this->getWebsiteCollection() as $_website): ?>
        <?php $showWebsite=false; ?>
        <?php foreach ($this->getGroupCollection($_website) as $_group): ?>
            <?php $showGroup=false; ?>
            <?php foreach ($this->getStoreCollection($_group) as $_store): ?>
                <?php if (!empty($scope) && !in_array($_store->getId(), $scope)): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <?php if ($showWebsite == false): ?>
                    <?php $showWebsite = true; ?>
                    <option disabled="disabled" value=""><?php echo $_website->getName() ?></option>
                <?php endif; ?>
                <?php if ($showGroup == false): ?>
                    <?php $showGroup = true; ?>
                    <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $_group->getName() ?>">
                <?php endif; ?>
                <option value="<?php echo $_store->getId() ?>"<?php if($this->getStoreId() == $_store->getId()): ?> selected="selected"<?php endif; ?>>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $_store->getName() ?></option>
            <?php endforeach; ?>
            <?php if ($showGroup): ?>
                </optgroup>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
</select>
</p>
<script type="text/javascript">
    function switchStore(obj){
        var storeParam = obj.value ? 'store/' + obj.value + '/' : '';
        if(obj.switchParams){
            storeParam+= obj.switchParams;
        }
        setLocation('<?php echo $this->getSwitchUrl() ?>'+storeParam);
    }
</script>
<?php endif; ?>
