<?php /* @var $this Unl_Payment_Block_Account_Edit */ ?>
<?php echo $this->getFormInitScripts() ?>
<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="content-buttons form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>

<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="edit_form">
    <?php echo $this->getFormHtml() ?>

    <?php echo $this->getAssignAccordionHtml() ?>
</form>

<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="content-buttons form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>
<?php echo $this->getFormScripts() ?>
