<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
<script type="text/javascript">
//<![CDATA[
    var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
//]]>
</script>
    <p class="availability in-stock"><span><?php echo $_product->getStockItem()->getManageStock() ? $this->__('In stock') : $this->__('Available') ?></span></p>
<?php elseif ($_product->getNoSale()): ?>
    <p class="availability no-sale"><span><?php echo $this->__('Not available online') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><span><?php echo $this->helper('catalog')->__('Out of stock') ?></span></p>
<?php endif; ?>
<div class="price-box-bundle">
    <?php echo $this->getPriceHtml($_product) ?>
</div>
<?php echo $this->getChildHtml('bundle_prices') ?>
