<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend <?php echo $this->getHeaderCssClass() ?>"><?php echo $this->getHeaderText() ?></h4>
     </div>

    <fieldset class="np">
    <div class="order-address">
        <div class="content">
            <?php echo $this->getForm()->toHtml() ?>
        </div>
        <div class="order-save-in-address-book">
        	<p>
                <input name="<?php echo $this->getForm()->getHtmlNamePrefix()?>[save_to_order]" type="checkbox" id="<?php echo $this->getForm()->getHtmlIdPrefix()?>save_to_order" value="1" />
                <label for="<?php echo $this->getForm()->getHtmlIdPrefix()?>save_to_order"><?php echo Mage::helper('sales')->__('Save to order') ?></label>
            </p>
            <p style="margin:0;">
            	<input type="checkbox" id="<?php echo $this->getForm()->getHtmlIdPrefix()?>address_enable" value="1" />
                <label for="<?php echo $this->getForm()->getHtmlIdPrefix()?>address_enable"><?php echo Mage::helper('sales')->__('Enable Edit') ?></label>
            </p>
        </div>
    </div>
    </fieldset>
</div>
<script type="text/javascript">
//<![CDATA[
(function() {
	var addressEnableCheck = $('<?php echo $this->getForm()->getHtmlIdPrefix()?>address_enable');
	if (addressEnableCheck) {
	    var saveAddressCheck = $('<?php echo $this->getForm()->getHtmlIdPrefix()?>save_to_order');
	    var bindAddressChange = function() {
	    	Form.getElements(addressEnableCheck.up(2)).each(function (el) {
		    	if (el == addressEnableCheck) {
			    	return true;
		    	}
			    el.disabled = !addressEnableCheck.checked;
		    });
	    };
	    Event.observe(addressEnableCheck, 'change', bindAddressChange);
	    bindAddressChange();
	}
})();
//]]>
</script>