<?php /* @var $this Unl_Ship_Block_Shipment_Create_Packages */ ?>
<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data" id="packages_table">
        <col />
        <col />
        <col width="1" />
        <col />
        <col />
        <col />
        <col />
        <col />
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Index') ?></th>
                <th><?php echo $this->helper('sales')->__('Container') ?></th>
                <th class="a-center"><?php echo $this->helper('sales')->__('Item Count') ?></th>
                <th class="a-center"><?php echo $this->helper('sales')->__('Weight') ?></th>
                <th><?php echo $this->helper('sales')->__('Extra Weight') ?></th>
                <th><?php echo $this->helper('sales')->__('Length') ?> <span class="required">*</span></th>
                <th><?php echo $this->helper('sales')->__('Width') ?> <span class="required">*</span></th>
                <th><?php echo $this->helper('sales')->__('Height') ?> <span class="required">*</span></th>
                <th class="last"><?php echo $this->helper('sales')->__('Tracking Number') ?></th>
            </tr>
        </thead>
        <tfoot>
        	<tr>
        		<td class="a-right last" colspan="9" style="padding: 8px;">
        			<?php echo $this->getChildHtml('add_button') ?>
        		</td>
        	</tr>
        </tfoot>
        <tbody id="package_row_container">
        	<tr id="package_row_template" class="template no-display">
        		<td id="package_index___index__">__index__</td>
        		<td>
        			<select name="packages[__index__][container]" class="select package-container" disabled="disabled">
                        <?php foreach ($this->getContainers() as $_option): ?>
                        <option value="<?php echo $_option['value'] ?>"><?php echo $_option['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
        		</td>
        		<td class="a-center"><span class="item-count" id="package_item_count___index__">0</span></td>
        		<td class="a-center"><span id="package_weight___index__">0</span></td>
        		<td>
        			<input class="input-text package-weight-extra validate-zero-or-greater" id="package_weight_extra___index__" name="packages[__index__][weight_extra]" value="0" disabled="disabled" />
        		</td>
        		<td>
        			<input class="input-text package-length required-entry validate-greater-than-zero" id="package_length___index__" name="packages[__index__][length]" value="0" disabled="disabled" />
        		</td>
        		<td>
        			<input class="input-text package-width required-entry validate-greater-than-zero" id="package_width___index__" name="packages[__index__][width]" value="0" disabled="disabled" />
        		</td>
        		<td>
        			<input class="input-text package-height required-entry validate-greater-than-zero" id="package_height___index__" name="packages[__index__][height]" value="0" disabled="disabled" />
        		</td>
        		<td class="last a-center">
        			<button class="scalable delete icon-btn delete-package-option" onclick="packageControl.deleteRow(event);return false;" type="button" title="<?php echo $this->helper('sales')->__('Delete') ?>"><span><?php echo $this->helper('sales')->__('Delete') ?></span></button>
        		</td>
        	</tr>
        </tbody>
    </table>
  </div>
</div>
<script type="text/javascript">
//<![CDATA[
var packageControl = {
	index : 0,
	template : new Template('<tr>' + $('package_row_template').innerHTML.replace(/__index__/g, '#{index}') + '<\/tr>'),
	containerDimensions : <?php echo Mage::helper('core')->jsonEncode($this->getContainerDimensions()) ?>,
    add : function () {
        this.index++;
        var data = {index:this.index};
        Element.insert($('package_row_container'), {bottom: this.template.evaluate(data)});
        var newRow = $('package_index_' + this.index).up();
        Form.getElements(newRow).each(function(el) {
			el.enable();
        });
        this.bindContainerOnchange(newRow);
        this.bindExtraWeightOnchange(newRow);
        $('package_items_table').select('.package-item-package').each(function(el) {
            var op = new Element('option', {value:this.index});
            op.update(this.index);
            el.insert(op);
        }.bind(this));
    },
    deleteRow : function(event) {
        if ($('package_row_container').select('tr').length <= 2) {
            alert('<?php echo $this->helper('sales')->__('Cannot delete the last package') ?>');
            return false;
        }
        var row = Event.findElement(event, 'tr');
        if (row) {
            var idx = row.select('td')[0].innerHTML;
            $('package_items_table').select('.package-item-package').each(function(el) {
                el.select('option').each(function(op) {
                    if (op.value == idx) {
                        op.remove();
                        return false;
                    }
                });
            });
            row.parentNode.removeChild(row);
        }
    },
    bindExtraWeightOnchange: function(el) {
        var exWeight = el.select('.package-weight-extra')[0];
        exWeight.observe('change', function(evt) {
            var elem = Event.element(evt);
            var idx = elem.up('tr').down().innerHTML;
			packageItemControl.recalculatePackageWeight(idx);
        });
    },
    bindContainerOnchange : function(el) {
        var cont = el.select('.package-container')[0];
        cont.observe('change', function(event) {
            var elem = Event.element(event);
            this.containerOnchange(elem);
        }.bind(this));
        this.containerOnchange(cont);
    },
    containerOnchange : function(elem) {
    	if (this.containerDimensions[$F(elem)]) {
            var dims = this.containerDimensions[$F(elem)];
            var row = elem.up(1);
            row.select('.package-length')[0].setValue(dims['length']);
            row.select('.package-width')[0].setValue(dims['width']);
            row.select('.package-height')[0].setValue(dims['height']);
        }
    }
};
packageControl.add();
//]]>
</script>