<?php
/**
 * Customer onepage checkout login form template
 *
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>
<div class="col2-set login-set">
    <?php echo $this->getChildHtml('login_before')?>
    <div class="col-1">
        <h3><?php echo $this->__('Login') ?></h3>
        <div class="buttons-set">
            <p class="disclaimer">Are you UNL Student, Faculty, or Staff?</p>
            <button type="button" class="button btn-unl-login" title="<?php echo $this->__('UNL Login') ?>" onclick="setLocation('<?php echo Mage::helper('unl_cas')->getCasUrl() ?>');"><span><span><?php echo $this->__('UNL Login') ?></span></span></button>
        </div>
        <div class="buttons-set">
            <p class="disclaimer">Not UNL Student, Faculty, or Staff, but <strong>previously registered</strong>?</p>
            <button type="button" class="button" onclick="$('login-form-wrapper').toggleClassName('invisible');"><span><span><?php echo $this->__('Customer Login') ?></span></span></button>
        </div>
    </div>
    <div class="col-2">
        <?php $errors = $this->getMessagesBlock()->getGroupedHtml(); ?>
        <div id="login-form-wrapper" class="<?php echo empty($errors) ? 'invisible' : '' ?>">
            <?php echo $errors ?>
            <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <fieldset>
                <p><?php echo $this->__('Please log in below:') ?></p>
                <p class="disclaimer">Do <strong>not</strong> use the form below if you are logging in as UNL Student, Faculty, or Staff.</p>
                <ul class="form-list">
                    <li>
                        <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                </ul>
                <input name="context" type="hidden" value="checkout" />
            </fieldset>
            </form>
            <div class="buttons-set">
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
                <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
            </div>
        </div>
    </div>
</div>
<div class="col2-set">
    <div class="col-1">
        <h3><?php if($this->getQuote()->isAllowedGuestCheckout()): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
        <div class="buttons-set">
            <?php if ($this->getQuote()->isAllowedGuestCheckout() ): ?>
            <button id="login:guest" type="button" class="button" onclick="onepageCheckout(this);"><span><span><?php echo $this->__('Guest Checkout') ?></span></span></button>
            <?php endif; ?>
            <button id="login:register" type="button" class="button" onclick="onepageCheckout(this);"><span><span><?php echo $this->__('Register') ?></span></span></button>
        </div>
        <?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?>
            <input type="hidden" name="checkout_method" id="login:method" value="register" />
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:method" value="guest" />
        <?php endif; ?>
    </div>
    <div class="col-2">
        <p>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <strong><?php echo $this->__('Register and save time!') ?></strong><br />
        <?php endif; ?>
        <?php echo $this->__('Register with us for future convenience:') ?>
        </p>
        <ul class="ul">
            <li><?php echo $this->__('Fast and easy check out') ?></li>
            <li><?php echo $this->__('Easy access to your order history and status') ?></li>
        </ul>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
    function onepageCheckout(button) {
        var method;
    	<?php if (!$this->getQuote()->isAllowedGuestCheckout() ): ?>
    	method = 'register';
    	<?php else: ?>
        if (button.id == 'login:guest') {
            method = 'guest';
        } else {
        	method = 'register';
        }
    	<?php endif; ?>

    	$('login:method').value = method;
        checkout.setMethod();
    };
//]]>
</script>
