<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/* @var $this Mage_Checkout_Block_Onepage_Login */
?>
<?php $_allowGuest = $this->getQuote()->isAllowedGuestCheckout(); ?>
<?php $_mustBeLogged = $this->helper('checkout')->isCustomerMustBeLogged(); ?>
<?php echo $this->getChildHtml('login_before')?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="wdn-grid-set-halves bp2-wdn-grid-set-<?php echo $_allowGuest ? 'fourths' : 'thirds' ?>">
    <div class="wdn-col" id="unl_login">
        <a class="mrkp-btn-cnt" href="<?php echo Mage::helper('unl_cas')->getCasUrl(true) ?>">
            <i class="mrkp-icon-unl-n"></i>
            <span class="mrkp-btn-action">Log in as</span>
            <span class="mrkp-btn-noun">UNL <span style="display:block;font-size:.7em">student, faculty, staff</span></span>
        </a>
    </div>
    <div class="wdn-col" id="returning">
        <a class="mrkp-btn-cnt" href="#">
            <i class="mrkp-icon-login"></i>
            <span class="mrkp-btn-action">Log in as</span>
            <span class="mrkp-btn-noun short">returning customer</span>
        </a>
    </div>
    <div class="bp2-wdn-col-<?php echo $_allowGuest ? 'three-fourths' : 'two-thirds' ?>" id="login_inputs" style="display:none;">
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <fieldset>
            <ul class="form-list">
                <li>
                    <label for="login-email" class="required"><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="login-email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password" class="required"><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" name="login[password]" class="input-text required-entry validate-password" id="login-password" title="<?php echo $this->__('Password') ?>" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <input name="context" type="hidden" value="checkout" />

            <div class="buttons-set">
                <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                <a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
            </div>
        </fieldset>
        </form>
    </div>
    <div class="wdn-col" id="create">
    <?php if (!$_allowGuest && $_mustBeLogged): ?>
        <input type="hidden" id="login:register" value="register" />
        <?php $_onClick = 'setLocation(\'' . $this->helper('checkout/url')->getRegistrationUrl() . '\')'; ?>
    <?php else: ?>
        <input type="radio" name="checkout_method" id="login:register" value="register" <?php echo !$_allowGuest ? ' checked="checked"' : '' ?> class="radio no-display" />
        <?php $_onClick = 'persistentContinue(' . (!$_allowGuest ? 'true' : '') . ')' ; ?>
    <?php endif;?>
        <label class="mrkp-btn-cnt" for="login:register" onclick="<?php echo $_onClick ?>">
            <i class="wdn-icon-user"></i>
            <span class="mrkp-btn-action">Register as</span>
            <span class="mrkp-btn-noun short">new customer</span>
        </label>
    </div>
    <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
    <div class="wdn-col" id="login_guest">
        <input type="radio" name="checkout_method" id="login:guest" value="guest" onclick="persistentContinue()" class="radio no-display" />
        <label class="mrkp-btn-cnt" for="login:guest">
            <i class="mrkp-icon-forward"></i>
            <span class="mrkp-btn-action">Continue as</span>
            <span class="mrkp-btn-noun short">guest</span>
        </label>
    </div>
    <?php endif; ?>
</div>

<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    require(['jquery', 'modernizr'], function($, Modernizr) {
		$(function() {
			$('#returning a').on('click', function(e) {
    			var unlLogin = $('#unl_login'),
    			create = $('#create'),
    			unlLoginBtn = unlLogin.children('a'),
    			loginForm = $('#login_inputs'),
    			guest = $('#login_guest'),
    			$this = $(this),
    			st = 'state',
    			tg = 'toggle',
    			w = 'width',
    			h = 'height',
    			bp1 = '(min-width: 480px)';

    			e.preventDefault();

    			if (!$this.data(st)) {
    				$this.data(st, true);

    				var done = function() {
    					loginForm.fadeIn();
    				},
    				ani = {opacity: 0};

    				if (Modernizr.mq(bp1)) {
    					unlLoginBtn.width(unlLoginBtn.width());
        				ani[w] = tg;
    				} else {
    					ani[h] = tg;
    				}

    				unlLogin.animate(ani, done);
    				create.fadeOut();
    				guest.fadeOut();
    			} else {
    				$this.data(st, false);

    				var done = function() {
    					unlLoginBtn.css(w, '');
    				},
    				ani = {opacity: 1};

    				loginForm.fadeOut(function() {
        				if (Modernizr.mq(bp1)) {
        					ani[w] = tg;
        				} else {
        					ani[h] = tg;
        				}

        				unlLogin.animate(ani, done);
        				create.fadeIn();
        				guest.fadeIn();
    				});
    			}
    		});
		});
    });

    function persistentContinue(register){
        if (register) {
        	new Ajax.Request('<?php echo $this->getUrl('persistent/index/saveMethod'); ?>', {
            	method: 'post',
            	onFailure: function() {
                	checkout.ajaxFailure();
            	}
        	});
        }

        checkout.setMethod();
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
