<div class="col2-set">
    <h3><?php echo $this->__('Address Book') ?> <span class="heading-link"><a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a></span></h3>
    <div class="col-1">
        <div class="sec_main neutral">
            <h4><?php echo $this->__('Default Billing Address') ?> <span class="heading-link"><a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a></span></h4>
            <address>
                <?php echo $this->getPrimaryBillingAddressHtml() ?>
            </address>
        </div>
    </div>
    <div class="col-2">
        <div class="sec_main neutral">
            <h4><?php echo $this->__('Default Shipping Address') ?> <span class="heading-link"><a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a></span></h4>
            <address>
                <?php echo $this->getPrimaryShippingAddressHtml() ?>
            </address>
        </div>
    </div>
</div>
