<div class="col2-set">
    <div class="col-1">
        <div class="sec_main neutral">
            <h3><?php echo $this->__('Contact Information') ?> <span class="heading-link"><a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a></span></h3>
            <p>
                <?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br />
                <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
                <?php if (Mage::helper('unl_cas')->isAllowedAffiliationSwitch($this->getCustomer())): ?>
                <?php $_affiliations = Mage::helper('unl_cas')->getAffiliations(); ?>
                <?php echo $this->__('Current Shopping Affiliation') ?>: <strong><?php echo (Mage::helper('unl_cas')->getCustomerAffiliation($this->getCustomer())) ? array_search(Mage::helper('unl_cas')->getCustomerAffiliation($this->getCustomer()), $_affiliations) : ''?></strong><br />
                <?php endif; ?>
                <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
            </p>
        </div>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="col-2">
        <div class="sec_main cool">
            <h3><?php echo $this->__('Newsletters') ?> <span class="heading-link"><a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a></span></h3>
            <p>
                <?php if( $this->getIsSubscribed() ): ?>
                    <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                <?php else: ?>
                    <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                <?php endif; ?>
            </p>
        </div>
    </div>
    <?php endif; ?>
</div>
