<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
            <?php echo $this->getChildHtml('cms_footer_links'); ?>
            <div class="footer_col">
                <h3>Helpful Pages</h3>
                <?php echo $this->getChildHtml('footer_links'); ?>
            </div>
            
            <div id="copyright">
                <?php echo $this->getChildHtml('newsletter') ?>
                <?php echo $this->getCopyright(); ?>
                <ul>
                    <li><a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a></li>
                    <li><a href="http://validator.unl.edu/check/referer">W3C</a></li>
                    <li><a href="http://www1.unl.edu/feeds/">RSS</a></li>
                </ul>
                <a href="http://www.unl.edu/" title="UNL Home"><img src="/ucomm/templatedependents/templatecss/images/wordmark.png" alt="UNL's wordmark" id="wordmark" /></a>
            </div>
