<title><?php echo $this->getTitle() ?></title>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />

<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
    var SKIN_URL = '<?php echo $this->helper('core/js')->getJsSkinUrl('') ?>';
</script>

<!-- Codebase:UNLFramework 20071011 -->
<link rel="stylesheet" type="text/css" media="screen" href="/ucomm/templatedependents/templatecss/layouts/main.css" />
<link rel="stylesheet" type="text/css" media="print" href="/ucomm/templatedependents/templatecss/layouts/print.css"/>
<script type="text/javascript" src="/ucomm/templatedependents/templatesharedcode/scripts/all_compressed.js"></script>

<?php virtual('/ucomm/templatedependents/templatesharedcode/includes/browsersniffers/ie.html'); ?>
<?php virtual('/ucomm/templatedependents/templatesharedcode/includes/comments/developersnote.html'); ?>
<?php virtual('/ucomm/templatedependents/templatesharedcode/includes/metanfavico/metanfavico.html'); ?>

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>

<?php echo $this->helper('core/js')->getTranslatorScript() ?>
