<?php /* @var $this Unl_Core_Block_Page_Html_Affiliatecrumbs */ ?>
<?php if($crumbs && is_array($crumbs)): ?>
<?php foreach($crumbs as $_crumbName => $_crumbInfo): ?>
    <?php if ($_crumbName === 'home') { continue; } ?>
    <li class="<?php echo $_crumbName ?>">
    <?php if($_crumbInfo['link']): ?>
        <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
    <?php else: ?>
        <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
    <?php endif; ?>
    </li>
<?php endforeach; ?>
<?php endif; ?>
