<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
    <ul class="form-list checkmo-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <p class="mrkp-notice clearer"><i class="wdn-icon-attention"></i>We will not process or ship your order until <em>complete</em> payment is received and cleared.</p>
        </li>
        <?php if ($this->getMethod()->getPayableTo()): ?>
        <li>
            <span class="label"><?php echo $this->__('Make Check payable to:') ?></span>
            <output id="checkmo_payto" class="output"><?php echo $this->escapeHtml($this->getMethod()->getPayableTo()) ?></output>
        </li>
        <?php endif; ?>
        <?php if ($this->getMethod()->getMailingAddress()): ?>
        <li>
            <span class="label"><?php echo Mage::helper('payment')->__('Send Check to:') ?></span>
            <address id="checkmo_mailto" class="checkmo-mailing-address output">
                <?php echo nl2br($this->escapeHtml($this->getMethod()->getMailingAddress())) ?>
            </address>
        </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
