<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <p class="mrkp-notice clearer"><i class="wdn-icon-attention"></i>By entering your cost object below, you are asserting that you are authorized to make purchases with it and giving us authorization to issue internal charges to cover the order total.</p>
    </li>
    <li>
        <label for="po_number" class="required"><em>*</em><?php echo $this->__('Purchase Order Number') ?></label>
        <div class="input-box">
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo $this->__('Purchase Order Number') ?>" class="input-text required-entry validate-costobject" value="<?php echo $this->htmlEscape($this->getInfoData('po_number')) ?>" />
        </div>
    </li>
</ul>
<script type="text/javascript">
Validation.add('validate-costobject', 'Please enter a valid cost object number', function(v, elem) {
    v = v.replace(/\-|\s/g, '');
    return Validation.get('IsEmpty').test(v) || ( !/[^\d]/.test(v) && ( v.length == 10 || v.length == 13 ) );
});
</script>
