<?php
/**
 * Template for Mage_Block_Adminhtml_Report_Grid
 *
 *  getId()
 *  getCollection()
 *  getColumns()
 *  getPagerVisibility()
 *  getVarNamePage()
 */
/* @var $this Unl_Core_Block_Adminhtml_Report_Product_Customized_Grid */
?>
<?php if($this->getCollection()): ?>
    <?php if($this->canDisplayContainer()): ?>
        <?php if($this->getGridHeader()): ?>
        <div class="content-header">
            <table cellspacing="0">
                <tr>
                    <td style="width:50%;"><h2><?php echo $this->getGridHeader(); ?></h2></td>
                </tr>
            </table>
        </div>
        <?php endif ?>
        <div id="<?php echo $this->getId() ?>">
    <?php else: ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php endif; ?>
    <?php if($this->getStoreSwitcherVisibility() || $this->getDateFilterVisibility()): ?>
        <?php if($this->getStoreSwitcherVisibility()): ?>
            <?php echo $this->getStoreSwitcherHtml() ?>
        <?php endif ?>
        <table cellspacing="0" class="actions">
            <tr>
        <?php if($this->getDateFilterVisibility()): ?>
            <td class="a-left filter">
                <div class="f-left">
                    <div><?php echo $this->__('From') ?>:&nbsp;<input class="input-text no-changes required-entry" type="text" id="period_date_from" name="report_from" value="<?php echo $this->getFilter('report_from') ?>" style="width:5em" /> <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" title="<?php echo $this->__('Select Date') ?>" id="period_date_from_trig" alt="<?php echo $this->__('Select Date') ?>" class="v-middle"/>&nbsp;&nbsp;</div>
                    <div id="period_date_from_advaice"></div>
                </div>

                <div class="f-left">
                    <div><?php echo $this->__('To') ?>:&nbsp;<input  class="input-text no-changes required-entry" type="text" id="period_date_to" name="report_to"  value="<?php echo $this->getFilter('report_to') ?>" style="width:5em" /> <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" class="v-middle" title="<?php echo $this->__('Select Date') ?>"id="period_date_to_trig" alt="<?php echo $this->__('Select Date') ?>"/>&nbsp;&nbsp;</div>
                    <div id="period_date_to_advaice"></div>
                </div>

                <div class="f-left">
                    <div><?php echo $this->__('SKU') ?>:&nbsp;<input  class="input-text no-changes" type="text" id="filter_sku" name="sku"  value="<?php echo $this->getFilter('sku') ?>" style="width:10em" />&nbsp;&nbsp;</div>
                    <div id="filter_sku_advaice"></div>
                </div>
                
                <div class="f-left">
                    <?php echo $this->getRefreshButtonHtml() ?>
                </div>
                <script type="text/javascript">
                <!--
                Calendar.setup({
                    inputField : 'period_date_from',
                    ifFormat : '<?php echo $this->getDateFormat() ?>',
                    button : 'period_date_from_trig',
                    align : 'Bl',
                    singleClick : true
                });
                Calendar.setup({
                    inputField : 'period_date_to',
                    ifFormat : '<?php echo $this->getDateFormat() ?>',
                    button : 'period_date_to_trig',
                    align : 'Bl',
                    singleClick : true
                });
                //-->
                </script>
            </td>
        <?php endif; ?>
        <?php if($this->getExportVisibility()): ?>
            <td class="a-right">
                <img src="<?php echo $this->getSkinUrl('images/icon_export.gif') ?>" alt="" class="v-middle"/>&nbsp; <?php echo $this->__('Export to:') ?>
                <select name="<?php echo $this->getId() ?>_export" id="<?php echo $this->getId() ?>_export" style="width:8em;">
                <?php foreach ($this->getExportTypes() as $_type): ?>
                    <option value="<?php echo $_type->getUrl() ?>"><?php echo $_type->getLabel() ?></option>
                <?php endforeach; ?>
                </select>
                <?php echo $this->getExportButtonHtml() ?>
            </td>
        <?php endif; ?>
            </tr>
        </table>
    <?php endif; ?>

    <div class="grid">
    <table cellspacing="0" class="data" id="<?php echo $this->getId() ?>_table">
        <?php if ($this->getHeadersVisibility() || $this->getFilterVisibility()): ?>
            <thead>
                <?php if ($this->getHeadersVisibility()): ?>
                    <tr class="headings">
                    <th class="no-link" style="width:100px"><span class="no-br"><?php echo $this->getPeriodText() ?></span></th>
                    <th class="no-link"><span class="no-br"><?php echo $this->__('SKU') ?></span></th>
                    <th class="no-link"><span class="no-br"><?php echo $this->__('Product Name') ?></span></th>
                    <th class="no-link"><span class="no-br"><?php echo $this->__('Qty Ordered') ?></span></th>
                    <th class="no-link"><span class="no-br"><?php echo $this->__('Order #') ?></span></th>
                    <th class="no-link"><span class="no-br"><?php echo $this->__('Customer First Name') ?></span></th>
                    <th class="no-link"><span class="no-br"><?php echo $this->__('Customer Last Name') ?></span></th>
                    <th class="no-link last"><span class="no-br"><?php echo $this->__('Options') ?></span></th>
                    </tr>
                <?php endif; ?>
            </thead>
        <?php endif; ?>
        <tbody>
        <?php if ($this->getCollection()->isReady() && count($this->getCollection())): ?>
        <?php foreach ($this->getCollection() as $_index => $_item): ?>
            <tr>
            <?php 
            $_order = $_item->getOrder();
            if ($_order->getCustomerIsGuest()) {
                $customerFirstname = $_order->getBillingAddress()->getFirstname();
                $customerLastname  = $_order->getBillingAddress()->getLastname();
            } else {
                $customerFirstname = $_order->getCustomerFirstname();
                $customerLastname  = $_order->getCustomerLastname();
            }
            ?>
            <td><?php echo $this->formatDate($_order->getCreatedAtDate(), 'medium'); ?></td>
            <td><?php echo $_item->getSku() ?></td>
            <td><?php echo $_item->getName() ?></td>
            <td class="a-right"><?php echo $_item->getQtyOrdered() ?></td>
            <td><a href="<?php echo $this->getUrl('adminhtml/sales_order/view', array('order_id' => $_order->getId())); ?>"><?php echo $_order->getIncrementId() ?></a></td>
            <td><?php echo $this->escapeHtml($customerFirstname); ?></td>
            <td><?php echo $this->escapeHtml($customerLastname); ?></td>
            <td class="last">
                <table cellspacing="0">
                    <thead>
                    <tr>
                    <?php foreach($_item->getProductOptionByCode('options') as $option): ?>
                        <th><?php echo $this->escapeHtml($option['label']); ?></th>
                    <?php endforeach; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                    <?php foreach($_item->getProductOptionByCode('options') as $option): ?>
                        <td><?php echo $this->escapeHtml($option['print_value']); ?></td>
                    <?php endforeach; ?>
                    </tr>                    
                    </tbody>
                </table>
            </td>
            </tr>
        <?php endforeach; ?>
        <?php elseif ($this->getEmptyText()): ?>
            <tr>
              <td class="empty-text <?php echo $this->getEmptyTextClass() ?>" colspan="100"><?php echo $this->getEmptyText() ?></td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
    </div>
<?php if($this->canDisplayContainer()): ?>
</div>
<script type="text/javascript">
//<![CDATA[
    <?php echo $this->getJsObjectName() ?> = new varienGrid('<?php echo $this->getId() ?>', '<?php echo $this->getGridUrl() ?>', '<?php echo $this->getVarNamePage() ?>', '<?php echo $this->getVarNameSort() ?>', '<?php echo $this->getVarNameDir() ?>', '<?php echo $this->getVarNameFilter() ?>');
    <?php echo $this->getJsObjectName() ?>.useAjax = '<?php echo $this->getUseAjax() ?>';
    <?php if($this->getDateFilterVisibility()):?>
    <?php echo $this->getJsObjectName() ?>.doFilterCallback = validateFilterDate;
    var period_date_from = $('period_date_from');
    var period_date_to   = $('period_date_to');
    var filter_sku       = $('filter_sku');
    period_date_from.advaiceContainer = $('period_date_from_advaice');
    period_date_to.advaiceContainer = $('period_date_to_advaice');
    filter_sku.advaiceContainer = $('filter_sku_advaice');

    function validateFilterDate()
    {
        if (period_date_from && period_date_to) {
            return Validation.validate(period_date_from) && Validation.validate(period_date_to);
        }
        else {
            return true;
        }
    }
    <?php endif;?>
    /* Overwrite function from switcher.phtml widget*/
    function switchStore(obj){
        if (obj.options[obj.selectedIndex].getAttribute('website') == 'true') {
            var selectionType = 'website';
        } else if (obj.options[obj.selectedIndex].getAttribute('group') == 'true') {
            var selectionType = 'group';
        } else {
            var selectionType = 'store';
        }
        var storeParam = obj.value ? selectionType + '/' + obj.value + '/' : '';
        if(obj.switchParams){
            storeParam+= obj.switchParams;
        }
        var formParam = new Array('period_date_from', 'period_date_to', 'filter_sku');
        var paramURL = '';
        var switchURL = '<?php echo $this->getAbsoluteGridUrl(array('_current' => false)); ?>'.replace(/(store|group|website)\/\d+\//,'');

        for(var i=0;i<formParam.length;i++){
            if ($(formParam[i]).value && $(formParam[i]).name) {
                paramURL+= $(formParam[i]).name + '=' + escape($(formParam[i]).value) + '&';
            }
        }
        setLocation(switchURL + storeParam + '?' + paramURL);
    }
//]]>
</script>
<?php endif; ?>
<?php endif; ?>
