<?php $_invoice = $this->getInvoice() ?>
<?php $_order   = $this->getOrder() ?>
<?php if ($_invoice && $_order): ?>
<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th align="left" bgcolor="#ba0000" style="padding:3px 9px;line-height:1em;color:#FFF;font-size:12px;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Item') ?></th>
            <th align="left" bgcolor="#ba0000" style="padding:3px 9px;line-height:1em;color:#FFF;font-size:12px;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Sku') ?></th>
            <th align="center" bgcolor="#ba0000" style="padding:3px 9px;line-height:1em;color:#FFF;font-size:12px;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Qty') ?></th>
            <th align="right" bgcolor="#ba0000" style="padding:3px 9px;line-height:1em;color:#FFF;font-size:12px;font-family: Helvetica,Arial,sans-serif;"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>

    <?php $i=0; foreach ($_invoice->getAllItems() as $_item): ?>
    <?php if($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
    <tbody<?php echo $i%2 ? ' bgcolor="#eeeded"' : '' ?>>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>

    <tfoot>
        <?php echo $this->getChildHtml('invoice_totals')?>
    </tfoot>
</table>
<?php endif; ?>
