<?php echo $this->getMethod()->getTitle() ?>
<?php if($this->getInfo()->getAdditionalData()): ?>
    <?php if($this->getPayableTo()): ?><br /><?php echo Mage::helper('payment')->__('Make Check payable to: %s', $this->htmlEscape($this->getPayableTo())) ?><?php endif; ?>
    <?php if($this->getMailingAddress()): ?>
        <br />
        <label><?php echo Mage::helper('payment')->__('Send Check to:') ?></label>
        <div class="checkmo-mailing-address">
            <?php echo nl2br($this->htmlEscape($this->getMailingAddress())) ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
