<?php /* @var Mage_Wishlist_Model_Item $item */ ?>
<?php
$item = $this->getItem();
$product = $item->getProduct();
?>
<a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
    <img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(223); ?>" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
</a>
